### PR TITLE
Fix aliased helpers

### LINKED ISSUE #3641: Broken alias for getAllowedSizes
PR #3615 introduced some broken aliases after some helpers were moved:
```console
ale@avo:~/Code/plone/projects/coredev/6.0$ ./bin/zopepy 
>>> from Products.CMFPlone.utils import getAllowedSizes
<console>:1: DeprecationWarning: getAllowedSizes is deprecated. Import from plone.namedfile.utils instead (will be removed in Plone 7)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ale/.buildout/eggs/cp310/zope.deferredimport-4.4-py3.10.egg/zope/deferredimport/deferredmodule.py", line 71, in __getattr__
    v = get.get()
  File "/home/ale/.buildout/eggs/cp310/zope.deferredimport-4.4-py3.10.egg/zope/deferredimport/deferredmodule.py", line 55, in get
    return super(DeferredAndDeprecated, self).get()
  File "/home/ale/.buildout/eggs/cp310/zope.deferredimport-4.4-py3.10.egg/zope/deferredimport/deferredmodule.py", line 37, in get
    v = __import__(module, *self._import_chicken)
ModuleNotFoundError: No module named 'plone.namedfile.utils.getAllowedSizes'
```

### PR DESCRIPTION
**Pull request by ale-rt**
There was a typo, the last dot in the alias should be a column

Fixes #3641
Refs #3615

### CODE REVIEW

**Comment by ale-rt** [comment]
```console
ale@avo:~/Code/plone/projects/coredev/6.0$ ./bin/zopepy 
>>> from Products.CMFPlone.utils import getAllowedSizes
<console>:1: DeprecationWarning: getAllowedSizes is deprecated. Import from plone.namedfile.utils instead (will be removed in Plone 7)
>>> from Products.CMFPlone.utils import getQuality
<console>:1: DeprecationWarning: getQuality is deprecated. Import from plone.namedfile.utils instead (will be removed in Plone 7)
>>> from Products.CMFPlone.utils import getHighPixelDensityScales
<console>:1: DeprecationWarning: getHighPixelDensityScales is deprecated. Import from plone.namedfile.utils instead (will be removed in Plone 7)
```

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
Test fail with:
```
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 100
```

**Review by davisagli — APPROVED** [review]
LGTM. The robot tests have been failing on jenkins node 4. I could retry them to try to run on a different node, but if this error was not caught before, I don't think even passing tests will confirm it is fixed. You demonstrated it working on the console. So I'd say go ahead and merge.

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Review by gforcada — APPROVED** [review]

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
Also 3.10 was successful but failed to report back (known issue).
I am merging

**Pull request merged**
