### PR TITLE
Add missing closing bracket - fixes #3252

### LINKED ISSUE #3252: Fix closing curly brace in search.pt template
### What I did:

- opened Products/CMFPlone/browser/templates/search.pt in text editor (VS Code)
- try to collapse particular tags
- not all tags collapse because of the missing closing curly brace

### What I expect to happen:

- all tags need to close 'pretty'
- all opening curly braces need to have a closing one.

### PR DESCRIPTION
**Pull request by balavec**

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM

@jenkins-plone-org please run jobs

**Review by petschki — APPROVED** [review]
👍🏼

**Comment by mauritsvanrees** [comment]
Fine to merge by yourself once Jenkins is green.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by balavec** [comment]
Cool. Waiting for Jenkins to finish.

**Comment by petschki** [comment]
@mauritsvanrees seems that jenkins got stuck again ...

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I don't remember if the "please run jobs" comment ever worked for Plone 6 jobs. I think that is not hooked up yet. The checks above *did* say something like they were waiting, I don't know the exact words, but nothing happened.
I did not see any jobs running for this PR, so I manually started them. Now it says "Pending — Job started, wait until it finishes".

**Pull request merged**
