### PR TITLE
Optional hook to customize breadcrumbs like navigation

### PR DESCRIPTION
**Pull request by jensens**
Navigation already has this hook, same for breadcrumbs.

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]

**Comment by ale-rt** [comment]
Fine to merge, but you could also do:
```python
class CustomPhysicalNavigationBreadcrumbs(PhysicalNavigationBreadcrumbs):

     def breadcrumbs(self):
           breadcrumbs = super().breadcrumbs()
           # Do whatever you need on the breadcrumbs
           return breadcrumbs
```

It looks to me more pythonic and powerful and basically requires the same effort (register a custom view which extends the base view plus some code to fiddle with the default Plone one)

**Comment by jensens** [comment]
I could, but this way I do not have access to the original contexts of the breadcrumbs and would need to replicate all the code just for one line change. Having a callback per item is way more handy.

**Comment by ale-rt** [comment]
> I could, but this way I do not have access to the original contexts of the breadcrumbs and would need to replicate all the code just for one line change. Having a callback per item is way more handy.

Good point! It definitely makes sense to me now!

**Pull request merged**
