### PR TITLE
Added 2 imaging schema: plone.lead_scale_name and plone.is_lead_visible

### PR DESCRIPTION
**Pull request by bsuttor**
This PR is related to plone/plone.app.contenttypes#339
It added 2 settings for plone app contenttypes behavior "leadimage".

Is it ok if I add a profile "v51/to_alpha2" into plone.app.upgrade with a registry.xml like this :

```
<?xml version="1.0"?>
<registry>
  <record name="plone.lead_scale_name">
    <field type="plone.registry.field.Choice">
        <title>Leadimage scale</title>
        <description>Please select scale which will be used.</description>
        <vocabulary>plone.app.vocabularies.ImagesScales</vocabulary>
    </field>
    <value>mini</value>
  </record>
  <record name="plone.is_lead_visible">
    <field type="plone.registry.field.Bool">
        <title>Show Leadimage in content</title>
    </field>
    <value>True</value>
  </record>
</registry> 
```

### CODE REVIEW

**Comment by bsuttor** [comment]
This is work in progress, I didn't add a 'validation change' at this moment

**Comment by bsuttor** [comment]
I choose to add a event handler when you modified allowed_sizes. 
If you try to delete a value used to leadimage scale, a 'portal message' is put on request and allowed_sizes value doesn't change.

With a invariant, you can not automatically reset old value of allowed_sizes when you try to remove a line used to leadimage scale.
With invariant, I'm not sure of what happens when you change value directly in registry view instead of imaging control panel.

**Comment by jensens** [comment]
LGTM - so there is just the upgrade step missing before we can merge this and the one in p.a.ct?

**Comment by pbauer** [comment]
I rebased this and got a traceback when creating a newsitem:

```
2017-08-29 11:32:31 ERROR Zope.SiteErrorLog 1503999151.20.234766244038 http://localhost:8080/Plone/news/asd/newsitem_view
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 137, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 261, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module a78be45c86bc90897368b1820e09c9a9.py, line 246, in render
  Module 95757202f7df48046ebf4e47a50c9cf0.py, line 1223, in render_master
  Module 95757202f7df48046ebf4e47a50c9cf0.py, line 180, in render_content
  Module z3c.pt.expressions, line 71, in render_content_provider
  Module zope.viewlet.manager, line 112, in update
  Module zope.viewlet.manager, line 118, in _updateViewlets
  Module plone.app.contenttypes.behaviors.viewlets, line 13, in update
  Module plone.app.contenttypes.behaviors.viewlets, line 21, in is_visible
  Module <decorator-gen-6>, line 2, in get_registry_record
  Module plone.api.validation, line 77, in wrapped
  Module plone.api.portal, line 300, in get_registry_record
  Module plone.registry.registry, line 82, in forInterface
KeyError: 'Interface `Products.CMFPlone.interfaces.controlpanel.IImagingSchema` defines a field `retina_scales`, for which there is no record.'

 - Expression: "provider:plone.abovecontenttitle"
 - Filename:   ... one/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 83: col 73)
 - Source:     ...
                                    ^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x111d66750>
               views: <ViewMapper - at 0x11326efd0>
               modules: <instance - at 0x10c868c68>
               args: <tuple - at 0x10bc8a050>
               here: <ImplicitAcquisitionWrapper asd at 0x111cc1280>
               user: <ImplicitAcquisitionWrapper - at 0x111cc1f00>
               nothing: <NoneType - at 0x10bbd8eb8>
               container: <ImplicitAcquisitionWrapper asd at 0x111cc1280>
               request: <instance - at 0x112de1830>
               wrapped_repeat: <SafeMapping - at 0x1132ff2b8>
               traverse_subpath: <list - at 0x110988518>
               default: <object - at 0x10bce0af0>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper asd at 0x111cc1280>
               view: <SimpleViewClass from /Users/pbauer/workspace/coredev/src/plone.app.contenttypes/plone/app/contenttypes/browser/templates/newsitem.pt newsitem_view at 0x11326ead0>
               translate: <function translate at 0x113008140>
               root: <ImplicitAcquisitionWrapper Zope at 0x1118d11e0>
               options: {...} (0)
               target_language: <NoneType - at 0x10bbd8eb8>
```

**Pull request closed without merging**
