### PR TITLE
Removed isExpired.py skin script

### PR DESCRIPTION
**Pull request by reinhardt**
See #1801

### CODE REVIEW

**Comment by gforcada** [comment]
Build broken! 😃 at least the 5.2 seems to be broken due to missing this script

**Comment by gforcada** [comment]
@reinhardt @ale-rt I reverted the change, please although it can be annoying, always trigger the pull request jobs!

**Comment by reinhardt** [comment]
I'm pretty sure the build was green, but I should have explicitly mentioned the other two dependent PRs that need to be merged first. My bad!

**Comment by ale-rt** [comment]
Ops! Yeah the build was green and I did not notice it was dependant on other PRs! Sorry :/

**Pull request merged**
