### PR TITLE
reset requirejs when plone legacy bundle is rendered to prevent errors

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
@bloodbare What do you think about this?

This is to address possible issues with legacy js files trying to use requirejs. See https://github.com/plone/Products.CMFPlone/issues/845

It seems harmless--just trying to prevent possible issues for people.

**Comment by bloodbare** [comment]
Yes its a bit harmless, why it should be a problem to load a require module on legacyjs ? I know its not a good pattern, but does it produce some error ? What I was worried related to that is that if the the bundle is not compiled correct, there is no way to force recompilation of legacyjs like bundles.

**Comment by vangheem** [comment]
See https://github.com/plone/Products.CMFPlone/issues/845 mismatch error can happen.

Right now, you can force re-compilation of legacy bundle by reordering the legacy resource list.

**Comment by bloodbare** [comment]
I see the error, shouldn't we register resources that are AMD ? btw I'm sad we can't just use requirejs modules on non compiled js, but I feel fine with this PR.

**Comment by vangheem** [comment]
Yes, users should register the resources AMD style but not all users do... Some users will only ever think about, "I need to include this file" and not know how to do dependency management.

**Comment by bloodbare** [comment]
I still think that people should register js that is using and use the Products.CMFPlone.resources.add_resource_on_request function to add an specific resource to their view.

**Comment by vangheem** [comment]
I agree...

**Pull request merged**
