### PR TITLE
Rename e-mail to email. Refs #622

### PR DESCRIPTION
**Pull request by jaroel**

### CODE REVIEW

**Comment by jaroel** [comment]
To much work for now.

**Comment by pbauer** [comment]
:email:

**Comment by jaroel** [comment]
http://jenkins.plone.org/job/pull-request-5.0/157/

**Comment by jaroel** [comment]
Rebased, should resolve the 'toolbar_position' failures.
http://jenkins.plone.org/job/pull-request-5.0/177/

**Pull request closed without merging**
