### PR TITLE
fix active tab in test-rendering-icons

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
hm ... can someone just hit merge here? it fixes only the active tab for `test-rendering-icons`

/cc @pbauer @jensens

**Comment by yurj** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
.oO( Jenkins is most flaky with robot tests at the moment )

**Pull request merged**
