### PR TITLE
[WIP] PLIP 3211 - Mockup ES6, remove RequireJS

### PR DESCRIPTION
**Pull request by thet**
PLIP #3211

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@MrTango there are 3 commits where youre name is there but not an Email known to Github. Please amend your Email to these commits or add the email from there to Gitub.

**Comment by jensens** [comment]
dont forget to undo the TMP commit if problem is solved.
https://github.com/plone/Products.CMFPlone/pull/3247/files/009a6a9e09ed7863816602e85d8cf5b58e6925f0..3e9ab29fd65de61bb6d4d566faf5961ecb73a518

**Review by mauritsvanrees — APPROVED** [review]
I left a review with some comments in the PLIP.
The code changes here make sense.

**Pull request merged**
