### PR TITLE
pre-cook legacy bundle so we do not do write on read

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
test running here: http://jenkins.plone.org/job/pull-request-5.0/246/

**Comment by vangheem** [comment]
@tisto @gforcada is there something wrong with jenkins? The results seem wrong: http://jenkins.plone.org/job/pull-request-5.0/246/

**Comment by vangheem** [comment]
one more try: http://jenkins.plone.org/job/pull-request-5.0/248/

**Comment by gforcada** [comment]
@vangheem if you look at the full console output http://jenkins.plone.org/job/pull-request-5.0/246/consoleFull

You can see an error message:

```
 File "/home/jenkins/.buildout/eggs/Products.GenericSetup-1.7.7-py2.7.egg/Products/GenericSetup/utils.py", line 509, in _importBody
    self._importNode(dom.documentElement)
  File "/home/jenkins/workspace/pull-request-5.0/src/Products.CMFPlone/Products/CMFPlone/resources/exportimport/resourceregistry.py", line 159, in _importNode
    cookWhenChangingSettings(self.context, legacy)
  File "/home/jenkins/workspace/pull-request-5.0/src/Products.CMFPlone/Products/CMFPlone/resources/browser/cook.py", line 48, in cookWhenChangingSettings
    response = subrequest(siteUrl + '/' + css)
  File "/home/jenkins/.buildout/eggs/plone.subrequest-1.6.10-py2.7.egg/plone/subrequest/__init__.py", line 72, in subrequest
    "Unable to get request, perhaps zope.globalrequest is not configured."
AssertionError: Unable to get request, perhaps zope.globalrequest is not configured.
```

I hope that makes sense for you :)

**Comment by vangheem** [comment]
Thanks @gforcada I should have looked more closely.

http://jenkins.plone.org/job/pull-request-5.0/253/

**Comment by gforcada** [comment]
@vangheem no problem, actually that's a bit of irritating from Jenkins, that whenever there's setUp errors that part of the traceback is not shown on the report you get, only if you look at the console output.

Maybe we should change zope.testrunner so that if a layer setup is broken do not run any test at all and show that traceback instead?

**Pull request merged**
