### PR TITLE
Remove quick installer code [6.0]

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Part of PLIP https://github.com/plone/Products.CMFPlone/issues/1775.

I think this can be tested and merged on its own.
Maybe the related `plone.app.upgrade` branch is needed.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Review by ale-rt — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
I don't know why the tests fail. Maybe the other package merges were needed anyway, or it was too crowded on Jenkins. The other PRs are merged now. Let's try again. I have started the jobs manually.

**Comment by mauritsvanrees** [comment]
Jenkins keeps having the same test failures. This is on Plone 6.0 with Python 3.6, 3.7 and 3.8. Locally, with 3.8, all is fine.
[Test failures](https://jenkins.plone.org/job/pull-request-6.0-3.8/46/testReport/) are in:

- `Products.CMFPlone csrf.txt`
- `plone.stringinterp.tests.wrapperTests.txt`
- Several tests in `plone.app.content.tests.test_widgets`

Does anyone know what causes this?
Maybe some test isolation issue?

**Comment by mauritsvanrees** [comment]
I am trying it with a slightly cleaned up coredev in https://github.com/plone/buildout.coredev/pull/683

**Comment by mauritsvanrees** [comment]
The coredev PR with this branch worked. I will merge both.

**Pull request merged**
