### PR TITLE
Deletion by acquisition

### PR DESCRIPTION
**Pull request by gotcha**
https://dev.plone.org/ticket/13603

Second part : deletion through menu Actions delete

### CODE REVIEW

**Comment by jensens** [comment]
Any update on this one?

**Comment by do3cc** [comment]
@saily you know whats the state here?

**Comment by jensens** [comment]
I really would like to merge this one. But still a changelog entry is missing.

**Comment by gotcha** [comment]
@jensens Changelog updated

**Comment by thet** [comment]
we probably want a forward port for Plone 5 too, altough object_delete.cpy is gone in Plone 5

**Comment by jensens** [comment]
merged after some rebase troubles.

**Comment by jensens** [comment]
@tisto: were is the revert PR?

**Comment by tisto** [comment]
I did not see any pr in the first place so I reverted manually.

**Comment by jensens** [comment]
well, i have no idea how to revert the revert as a PR then. if you tell me i'am happy to document it. Please NEVER revert manually, this creates more work than a broken test does. Usally there are no direct commits to main-line branches, they are always from PRs.

**Comment by tisto** [comment]
There was no pull request, sorry: https://github.com/plone/Products.CMFPlone/commits/4.3.x

Go to Products.CMFPlone on the fs and do a "revert <HASH>".

It is the responsibility of the person who merges the pull request to make sure all tests pass on jenkins. I simply can not put more effort into this. If there is a proper pull request I will do a proper pull request revert.

**Comment by do3cc** [comment]
jensens, I am not sure, if it is exactly this what you are looking for, but here you go:
Add modify .git/config to contain the fetch commands
```
[remote "origin"]
        url = git://github.com/plone/Products.CMFPlone.git
        fetch = +refs/heads/*:refs/remotes/origin/*
        fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
```

Then you can get the PR like this
```
git checkout pr/198
```
And get a patch
```
git diff origin/4.3.x..pr/198
```
of some sort.
It sucks, but at least its possible

**Comment by jensens** [comment]
@tisto, well, i have no idea why it doe not appear in history 

but THIS here is the PR I merged. Maybe its because its old, was rebased and you'd have to page through history? No idea, just a wild guess. 

And as I said it looked fine to me, the broken test setup with the faulty xml may have confused me.

**Pull request merged**
