### PR TITLE
remove unused code to create NavTree

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/329/

**Comment by mauritsvanrees** [comment]
+1.

I confirm it is not used in core Plone. There might be third party code that uses it. In my own customer code I see one place where createNavTree is used, but that is indeed code that inherits from plone.app.portlets.

**Comment by gforcada** [comment]
@jensens could you rebase?

**Comment by mauritsvanrees** [comment]
I merged it manually.  The only merge conflict, as expected, was in the CHANGES.rst.
I was hoping to prevent such conflicts with issue #1008, making rebases less needed, but sadly it seems this has no effect in the github UI.

**Pull request merged**
