### PR TITLE
Move PasswordResetTool from own product to here

### PR DESCRIPTION
**Pull request by tomgross**
Supersedes #1799

### CODE REVIEW

**Comment by tomgross** [comment]
Tests are green (https://github.com/plone/buildout.coredev/pull/261): Please merge until it fails again ;-)
It needs 

 - [ ] #1809
 - [ ] plone/plone.app.upgrade#92
 - [ ] https://github.com/plone/buildout.coredev/pull/261 (only 3e646ef8647b89142df99c8fc27a3dddbac2fc47) 

Thanks
Tom

**Comment by jensens** [comment]
cool, like to merge, but plone/plone.app.upgrade#92 is not green

**Comment by tomgross** [comment]
@jensens Thanks. The PR in plone/plone.app.upgrade and plone/Products.CMFPlone depend on each other and fail therefore individually. There reference is the PR in plone/buildout.coredev#261, which combines both PRs and turned now green.

**Comment by gforcada** [comment]
@tomgross as Jens already said on another PR you can test multiple pull requests in a single job, just put each PR URL on a line, the text between the textarea and the button says that already :-)

**Comment by tomgross** [comment]
@gforcada I know but this didn't work for the buildout itself, just for the products. I guess this is an edge case. The problem is that PasswordResetTool is referenced in the test part of buildout and the tests fail but with this PRs merged the product shouldn't be there alltogether.

**Comment by jensens** [comment]
I see, this is indeed an edge case. Well, it was green and the p.a.upgrade is green in 5.0 branch as well, so I think we're safe to merge

**Comment by jensens** [comment]
rebased, merged p.a..upgrade and removed from sources.cfg

I hope jenkins stays green after all 3 are run.

**Comment by tomgross** [comment]
@jensens @gforcada Thanks for the review, the tipps and the merge. The build indeed broke because of the reference to PasswordResetTool in the buildout. I removed it in https://github.com/plone/buildout.coredev/commit/8c168f7f6434633bab234caa1fa0d316a4bb8d81 and triggered the build http://jenkins.plone.org/job/plone-5.1-python-2.7/1005/
I expect it to return to green since the only failure was in PasswordResetTool.

**Comment by jensens** [comment]
Ok, I've overseen the reference in tests.cfg.thanks for the merge.

**Pull request merged**
