### PR TITLE
Remove controlpanel bbb adapter

### PR DESCRIPTION
**Pull request by jensens**
No more for Plone 4.3 settings compatibility

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
would be nice to get those removed. wait for plone.base merge first?

**Pull request closed without merging**
