### PR TITLE
Issue 1053 - Fix traceback style

### LINKED ISSUE #1053: Fix traceback message
Traceback message becomes ilegible:
traceback_before

if add a `whitespace: pre` into this tag css it will look a lot better:

traceback_after

### PR DESCRIPTION
**Pull request by rodfersou**
closes #1053

### CODE REVIEW

**Comment by rodfersou** [comment]
anyone can help me to compile this less file?

**Comment by rodfersou** [comment]
to compile it I had to delete these files in my buildout:

    * Gruntfile.js
    * node_modules/
    * temp_resources/

**Comment by rodfersou** [comment]
http://jenkins.plone.org/job/pull-request-5.0/372/

**Comment by jensens** [comment]
There is a failing test, but it does not make sense when looking at your changes. Try again:
http://jenkins.plone.org/job/pull-request-5.0/376/

**Pull request merged**
