### PR TITLE
Fix #1067: mail controlpanel not keeping password field when saving

### LINKED ISSUE #1067: mail controlpanel: doesn't keep password field
Saving the mail settings in the controlpanel doesn't keep the password field value, as it is obviously never shown in ESMTP password.

Steps to reproduce:

1. Fill in ESMTP username and ESMTP password. Save settings. They are correctly stored.
2. Apply save settings again. ESMTP password is incorrectly stored as None.

### PR DESCRIPTION
**Pull request by allusa**
ESMTP password is not shown in controlpanel, thus it is returned as None when saving #1067
@bloodbare

### CODE REVIEW

**Comment by allusa** [comment]
http://jenkins.plone.org/job/pull-request-5.0/396/

**Comment by tisto** [comment]
@allusa thanks for that fix! Do you think you could write a test for this? It should be pretty straight forward to add a test similar to that one:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_mail.py#L106

that just checks the form after the first save. I'm happy to assist you if you run into problems. Apart from that, this pr is ready for merge IMO.

**Comment by jensens** [comment]
i merge anyway to get things done. added an issue so we dont forget about it.

**Comment by tisto** [comment]
@jensens I intentionally did not merge that pr because I think we should take tests seriously. You saw that and decided to merge anyways. That's pretty rude IMHO.

I put a lot of effort into writing a lot of tests for this feature and it is really easy to write this particular test (maybe two lines of additional code). It would take me two minutes to write that test, but I wanted @allcaps to give it a try. 

Maybe I just ended up in the wrong community, if tests that take a few minutes to write are preventing us "to get things done"...

**Comment by jensens** [comment]
@tisto Sorry, i dont want to be rude. My apologies. IMO I took it serious by creating a new issue, set the label and ping @allcaps to ensure awareness, so the task get not lost . 

Usally i'd not merge, and wait, but try to let me explain why i did:
1. I reviewed the code, which is a very small and obvious change w/o much risk. The test is IMHO important not for now (in order to test if the code works), but to avoid future regressions.
2. I had the fear this one will block us releasing 5.0. In past it took weeks, month sometime years until something or nothing happened with PRs. So after merging hundreds of PRs in the last year I developed a pragmatic approach - merge + creating new tasks is one of them.  
3. I hope that the test will be created anyway soon. I know youre behind it and so it want get lost.
4. yes, get things done and lower the barrier to contribute 3-line changes is also important. we need to find a balance between both extremes (just pushing code and 100% test coverage)
5. I was not aware that the test only take a few minutes. I always end up in need of 5-10x more time for test, running it and checking it than for the actual code.

**Comment by tisto** [comment]
@jensens ok, my plan was to merge the pr later today and write the test myself if necessary. Though, I wanted to give @allusa a chance to do it himself.  I don't expect us to wait days or weeks for a test, or delay a release, but I have the feeling that we are not taking testing seriously enough sometimes. Let's get back to business, all good. Maybe I'm just a bit grumpy this morning because Barca lost the game yesterday... ;)

**Comment by allusa** [comment]
I have written the test #1072. 

@tisto  and  @jensens  many thanks for helping and giving opportunities to newbies!

**Comment by tisto** [comment]
@allusa awesome! Thanks! That was a very good first contribution. :)

**Comment by jensens** [comment]
:+1:

**Pull request merged**
