### PR TITLE
Move plone_content skins folder to ATCT as browser views

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by thet** [comment]
For Dexterity content types we have similar views in plone.app.contenttypes.

IMO the old CMFPlone folder listing related temaplates should go as refactored views (the work you have done) into Products.ATContentTypes.

**Comment by gforcada** [comment]
@thet done in this pull request and https://github.com/plone/Products.ATContentTypes/pull/39

**Comment by davisagli** [comment]
This is now passing together with https://github.com/plone/plone.app.dexterity/pull/232 and https://github.com/plone/Products.ATContentTypes/pull/39

**Comment by gforcada** [comment]
Merged!

**Pull request merged**
