### PR TITLE
New bundles for Plone 5.1.7

### PR DESCRIPTION
**Pull request by vincentfretin**
upgrade step here https://github.com/plone/plone.app.upgrade/pull/236

### CODE REVIEW

**Comment by vincentfretin** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
Thanks!

**Pull request merged**
