### PR TITLE
Remove the unused DefautDublincoreImpl

### PR DESCRIPTION
**Pull request by jensens**
Dead code, was only used in other dead code in plone.app.content, this is covered by https://github.com/plone/plone.app.content/pull/243, which needs to be merged first.

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM

**Review by pbauer — APPROVED** [review]

**Review by ale-rt — APPROVED** [review]
Wow... You are letting me know code that I never thought we had

**Pull request merged**
