### PR TITLE
Changed 'Powered by' text (Issue #3382)

### PR DESCRIPTION
**Pull request by rohnsha0**
changes as asked in #3382

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]

**Comment by rohnsha0** [comment]
@jenkins-plone-org please run jobs

**Comment by rohnsha0** [comment]
@stevepiercy @mauritsvanrees Kindly merge the PR!

**Comment by stevepiercy** [comment]
@rohnsha0 you must add a changelog entry. Please see the failed job "Changelog verifier" at the end of this issue.

**Comment by rohnsha0** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
