### PR TITLE
add missing i18n:translate calls

### LINKED ISSUE #2891: Several templates lack i18n:translate calls
As reported by https://jenkins.plone.org/view/Translations/job/plone-5.2-i18n-find-missing/lastSuccessfulBuild/artifact/missing.txt

### PR DESCRIPTION
**Pull request by erral**
Fixes #2891

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
I'm merging this to have the msgids translated before the 5.2 release

**Pull request merged**
