### PR TITLE
Fix password validation tests

### PR DESCRIPTION
**Pull request by tschorr**
Fix tests failing because of https://github.com/plone/Products.PlonePAS/pull/75, merge after that PR.

### CODE REVIEW

**Review by jensens — APPROVED** [review]

**Comment by tschorr** [comment]
@jenkins-plone-org please run jobs

**Comment by tschorr** [comment]
Failure in `pull-request-6.1-3.11` looks unrelated.

**Comment by tschorr** [comment]
@jenkins-plone-org please run jobs

**Comment by tschorr** [comment]
This time `pull-request-6.1-3.11` has passed, but it looks like the remaining Jenkins jobs are not started for some reason. Jenkins build queue is empty ...(?)

**Comment by tschorr** [comment]
@jenkins-plone-org please run jobs

**Comment by tschorr** [comment]
I'm stuck here. The `pull-request-6.0-3.x` Jenkins jobs never start (Jenkins build queue is empty), but they are required to run before I can merge the PR. @gforcada @davisagli any ideas?

**Comment by davisagli** [comment]
@tschorr I think I understand: this is targeting the master branch of CMFPlone, which is only used for Plone 6.1, so it is correct that it only triggers the builds for 6.1. However, the branch protection rules were not updated, so github was still expecting builds to run for 6.0. I just updated the branch protection rules so that only the Plone 6.1 job is required.

Since the change in PlonePAS is on a branch which is still used by both Ploen 6.0 and Plone 6.1, we also need this test fix in the 6.0.x branch of CMFPlone.

**Comment by davisagli** [comment]
@tschorr I submitted the backport in #3788

**Comment by tschorr** [comment]
> @tschorr I think I understand: this is targeting the master branch of CMFPlone, which is only used for Plone 6.1, so it is correct that it only triggers the builds for 6.1. However, the branch protection rules were not updated, so github was still expecting builds to run for 6.0. I just updated the branch protection rules so that only the Plone 6.1 job is required.
> 
> Since the change in PlonePAS is on a branch which is still used by both Ploen 6.0 and Plone 6.1, we also need this test fix in the 6.0.x branch of CMFPlone.

@davisagli thanks for sorting this out. I think I didn't see any differences between master and 6.0x when I created this PR and I didn't know that the master branch is only used for Plone 6.1.

**Pull request merged**
