### PR TITLE
Removing inconsistency in the 'Site Setup' links under Users settings

### PR DESCRIPTION
**Pull request by khanstark**
In Site Setup control panel, under Users and Groups there is inconsistency in the way parent link is displayed under different tabs like `Users`, `Groups`, `Settings`, and `Member Fields`...
Other categories in Site Setup have similar look-and-feel of this link.
ss1
<br><hr>
ss3

### CODE REVIEW

**Comment by jensens** [comment]
Please add a note to ``CHANGES.rst`` - the change log file.

**Comment by khanstark** [comment]
@jensens ignore initial commit in `CHANGES.rst`.

**Comment by gforcada** [comment]
@khanstark you need to rebase your branch and resolve the problems before it can be merged. Search for git rebase and resolve conflicts, you will find plenty of literature ;-)

**Comment by khanstark** [comment]
I thought I had a positive feedback on this, so I resolved the conflicts and merged it.
I don't think that would be a problem..!

**Comment by jensens** [comment]
@khanstark Whatever state it is, please NEVER merge a PR yourself. Golden Plone Rule #1 - thanks in advance.

**Comment by khanstark** [comment]
Golden Plone Rule No. 1----yeah I got it!

**Pull request merged**
