### PR TITLE
PLIP #3279: Implement modern image scales

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
@jenkins-plone-org please run jobs

**Review by ale-rt — APPROVED** [review]
Thanks @tisto for taking care of this!

I would also add an upgrade step to add the **new** scales if missing.
Not sure if we should edit the existing ones.
Also some documentation about the scales might be added somewhere.

Please also wait for the approval of some people from the classic team (CC @agitator @MrTango @petschki @thet)

**Comment by yurj** [comment]
Hi!
 can we just empty the default and let the profile handle it? @ale-rt introduced the upgrade steps need. So there would be an upgrade steps that delete "large", "preview" and "mini" when upgrading from 5.2 and add the new values. For 6.0, I would empty the default and have a profile with this new values. Hardcoded defaults (and they will change in the future) are hard to maintain, as we've seen, with a lot of work and discussion just to change a single value.

This values should be a config, as many other values in the control panel.

**Comment by tisto** [comment]
I am currently looking into the failing unit tests in plone.restapi. My time is rather limited these days and I would highly appreciate it if someone (@yurj @ale-rt @fredvd?) could help with the upgrade steps.

**Comment by fredvd** [comment]
@tisto @mauritsvanrees  I'm not sure if we need to provide an upgrade step here.  New Volto or Classic sites will get the proper default values when they are created.  integrators can and should overwrite the image scales with a GS profile. 

And when you upgrade A Plone 5.2 python3 Classic site to Plone 6.0 using in place migration, you'll need to look carefully at your probably customised theme and the impact here anyway. 

large will move from 768 width to 800.  But also all image heights in richtext area's that were bound to the max height will now scale according to the aspect ratio and could become much higher. Which will be most visible by portrait images. If you had a 400x800 image bound by the 400:400 scale, the image in the site would become 200x400 width. That's something you'll need to discuss with site users/owners about what to do here.

I don't think the impact is that big, but it will need a manual intervention anyway.  Better be explicit about it in the upgrade notes and not change/break things silently by rewriting the image scales in that case

**Comment by fredvd** [comment]
@tisto Failing tests in plone.restapi are 2 tests checking hardcoded against the 'existing' image scales in a default Plone5.2 sites.  

* test_namedimage_field_serialization_returns_dict_with_original_scale
* test_namedblobimage_field_serialization_returns_dict_with_original_scale

Maybe those tests should be rewritten to first insert a known image scale set and then test for only those scales coming back. Or query the image scale registry  field and do some basic math to calculate which scales at which sizes should be returned. 

--------

* https://github.com/plone/plone.restapi/blob/96e0bc119ecb847112b1310860b43e5c86cd5a54/src/plone/restapi/tests/test_dxfield_serializer.py#L376-L445

* https://github.com/plone/plone.restapi/blob/96e0bc119ecb847112b1310860b43e5c86cd5a54/src/plone/restapi/tests/test_dxfield_serializer.py#L504-L544

**Review by ale-rt — APPROVED** [review]

**Pull request merged**
