### PR TITLE
Fix and re-enable patch for zmi 

### LINKED ISSUE #2726: Message that the site needs to be upgraded and link to create plonesite are not displayed in new ZMI
The message "The site configuration is outdated and needs to be upgraded. Please continue with the upgrade." is not displayed in the ZMI. 

The reason is that the patch in `Products.CMFPlone.patches.addzmiplonesite` is deactivated because it patched the old dtml-file. 

The patch needs to be updated to patch the zpt-file `OFS/zpt/main.zpt`

### PR DESCRIPTION
**Pull request by pbauer**
Show link to add plone site and upgrade-warning. Fixes #2726 

This is pretty ugly layout-wise and code-wise. A better solution would be welcome but could also be added at any time.

### CODE REVIEW

**Comment by pbauer** [comment]
Damn, the patched `main.zpt` is run through RestrictedPython. So access to `obj.aq_chain` is blocked. 
Also: There is a small performance-hit. We should probably use a different approach. Ideas? 

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 128, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 276, in publish_module
  Module ZPublisher.WSGIPublisher, line 210, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 57, in call_object
  Module Shared.DC.Scripts.Bindings, line 330, in __call__
  Module Shared.DC.Scripts.Bindings, line 367, in _bindAndExec
  Module Products.PageTemplates.PageTemplateFile, line 141, in _exec
  Module Products.PageTemplates.PageTemplate, line 83, in pt_render
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module zope.pagetemplate.pagetemplate, line 265, in __call__
  Module zope.tal.talinterpreter, line 272, in __call__
  Module zope.tal.talinterpreter, line 344, in interpret
  Module zope.tal.talinterpreter, line 863, in do_condition
  Module Products.PageTemplates.Expressions, line 213, in evaluateBoolean
  Module zope.tales.tales, line 761, in evaluate
   - URL: main
   - Line 6, Column 0
   - Expression: <PythonExpr len(context.getPhysicalPath()) == 1 or context.meta_type == 'Folder' and 'PloneSite' not in [str(o) for o in context.aq_chain]>
   - Names:
      {'container': <Folder at /folder>,
       'context': <Folder at /folder>,
       'default': <object object at 0x10f1cde90>,
       'here': <Folder at /folder>,
       'loop': {},
       'nothing': None,
       'options': {'args': ()},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x118c00908>,
       'request': <WSGIRequest, URL=http://localhost:8080/folder/manage_main>,
       'root': <Application at >,
       'template': <PageTemplateFile at /folder/main>,
       'user': <PropertiedUser 'admin'>}
  Module Products.PageTemplates.ZRPythonExpr, line 49, in __call__
   - __traceback_info__: len(context.getPhysicalPath()) == 1 or context.meta_type == 'Folder' and 'PloneSite' not in [str(o) for o in context.aq_chain]
  Module PythonExpr, line 1, in <module>
  Module AccessControl.ImplPython, line 768, in guarded_getattr
  Module AccessControl.ImplPython, line 710, in aq_validate
  Module AccessControl.ImplPython, line 599, in validate
  Module AccessControl.ImplPython, line 237, in validate
  Module AccessControl.ImplPython, line 847, in raiseVerbose
Unauthorized: aq_* names (other than aq_parent, aq_inner, aq_explicit) are not allowed.  Access to 'aq_chain' of (Folder at /folder) denied.
```

**Comment by jensens** [comment]
@jenkins-plone-org please run tests

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
do we really need the link?

**Comment by pbauer** [comment]
I can live without it.

**Comment by petschki** [comment]
me too ;)

**Comment by jensens** [comment]
So lets skip it. @pbauer Do you close the PR please?

**Pull request closed without merging**
