### PR TITLE
Default to a 4K x 4K browser window in Robot tests

### PR DESCRIPTION
**Pull request by Rotonen**
I'm in the process of trying to unify Robot test setups and teardowns. This is a part of that effort.

Also re-enabled two previously disabled Robot tests.

In tandem with plone/plone.app.robotframework#110
Closes https://github.com/plone/Products.CMFPlone/issues/2864

### CODE REVIEW

**Comment by Rotonen** [comment]
I've done the work with a script.

At least `Products/CMFPlone/tests/robot/test_controlpanel_actions.robot` has actually changed in regards to how it is now set up.

I can still happily clean up and drop the meaningless capitalization changes, if so desired. I am not in any particular hurry with this process.

**Comment by mauritsvanrees** [comment]
If it is more consistent after this change, it is good.

**Comment by Rotonen** [comment]
Part of the stability is also future proofing stability over time. If we have the exact functionally same setups everywhere, local copy pasting will lead also to a new test, which works, and keeps working.

@jenkins-plone-org please run jobs

**Comment by Rotonen** [comment]
@mauritsvanrees I've also slipped through a botched changelog entry through here. Sorry.

**Comment by mauritsvanrees** [comment]
Okido, fixed on master in d1fcfd07972b65a8aeeb6a2b9f0f0f0da378c310. No problem.

**Pull request merged**
