### PR TITLE
small removal of Zope mention 

### PR DESCRIPTION
**Pull request by tkimnguyen**
...while logging out

### CODE REVIEW

**Comment by hvelarde** [comment]
why?

**Comment by jensens** [comment]
I personally dont care if there Zope in or not. But for the average user its superfluous information and so this PR is imo ok.

**Comment by gforcada** [comment]
:+1: there little to no benefit to know that it is Zope from a user interface point of view, just like we renamed the dexterity types control panel to be the types control panel, does not make sense to say that is dexterity (from plone 5 on)

**Comment by hvelarde** [comment]
I see, +1 then

**Comment by jensens** [comment]
@tkimnguyen please add a changelog entry and merge

**Comment by jensens** [comment]
@tkimnguyen nudge

**Comment by tkimnguyen** [comment]
Going to redo this (sorry for the delay) as a new PR with the changelog entry

**Comment by tkimnguyen** [comment]
New PR is here https://github.com/plone/Products.CMFPlone/pull/1457

**Pull request closed without merging**
