### PR TITLE
WIP remove portal metadata columns

### PR DESCRIPTION
**Pull request by gforcada**
See https://github.com/plone/Products.CMFPlone/issues/1279

### CODE REVIEW

**Comment by hvelarde** [comment]
-1 on merging this in Plone 5.0

**Comment by gforcada** [comment]
@hvelarde I hope you noticed the ``WIP`` and the related issue where I explain that is mostly an experiment right?

By no means this is meant to be merged, is just a way to see how much breakage will we get if we do so, and to trigger discussion around it.

But anyway, I will remove those and see how much it improves.

**Comment by jensens** [comment]
I think it's safe to close this one, as it was an experiment for #1279. Reopen if I am wrong.

**Comment by hvelarde** [comment]
@jensens you left the branch behind; that was on purpose?

**Comment by jensens** [comment]
Yes.

**Pull request closed without merging**
