### PR TITLE
Use "non-strict" parsing for `email.utils.getaddresses`

### LINKED ISSUE #4020: `email.utils.getaddresses` was changed to "strict-parsing" in Python 3.11.10 and 3.12.6
when running the tests we've encountered the following error in `testvalidateSingleEmailAddress`

```
AssertionError: True is not false : user@example.org
Bcc: user@example.org should fail
```

this is because `email.utils.getaddresses` has changed its strategy to "strict parsing" in the newest Python 3.11 and 3.12 versions. (see https://docs.python.org/3.12/whatsnew/3.12.html#id11 and https://docs.python.org/3.11/whatsnew/3.11.html#email)

### proposed solution:

~~add the parameter `strict=False` to get the old behavior back and test with `getattr(email.utils, 'supports_strict_parsing', False)` if this parameter is available~~

new approach: respect the new output from strict parsing.

### PR DESCRIPTION
**Pull request by petschki**
fixes #4020

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
It sounds a bit weird: the test expects that "email\nemail" fails, which it does not, and you fix it by being *less* strict.  I don't quite follow the logic, but I see locally that this fixes a test failure, also on Python 3.10.

**Comment by mauritsvanrees** [comment]
Can be merged when green.

**Comment by petschki** [comment]
in our case `strict=False` means "old parsing behavior" ... what I don't really understand is the new parsing behavior that when you do `getaddresses(["mail@mail.com\nmail@mail.com"])` you get `(["", ""])` back:

```
>>> email.utils.getaddresses(["mail@mail.com\nmail@mail.com"])
[('', '')]
>>> email.utils.getaddresses(["mail@mail.com\nmail@mail.com"], strict=False)
[('', 'mail@mail.com'), ('', 'mail@mail.com')]
>>>
```

**Comment by yurj** [comment]
https://github.com/python/cpython/issues/102988 maybe this?

**Comment by petschki** [comment]
Update: I think we should update the email validation to follow the actual strict behavior. So inputs like `email@mail.com\n email@mail.com` aren't valid anymore. But I found out, that if you separate mails only with a comma it returns the expected result:

### python 3.11.10
```
>>> email.utils.getaddresses(["user@example.org,\n user2@example.org"])
[('', 'user@example.org'), ('', 'user2@example.org')]
>>> email.utils.getaddresses(["user@example.org\n user2@example.org"])
[('', '')]
```

### python 3.11.5
```
>>> email.utils.getaddresses(["user@example.org,\n user2@example.org"])
[('', 'user@example.org'), ('', 'user2@example.org')]
>>> email.utils.getaddresses(["user@example.org\n user2@example.org"])
[('', 'user@example.org'), ('', 'user2@example.org')]
```


So in addition to the `len()` I'd check for the fallback return value `[('', '')]` here https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/PloneTool.py#L163

What do you think?

**Comment by mauritsvanrees** [comment]
What I still don't get is why these tests pass fine on Jenkins with the CMFPlone master branch, but locally they fail.
Ah, if you already get a difference between Python 3.11.10 and 3.11.15, then that may be the explanation.  Locally I have all the latest bugfix releases installed, and Jenkins probably lags a bit behind.

Also, https://docs.python.org/3/library/email.utils.html says the "strict" parameter was introduced in 3.13.  But the links you pointed to in issue #4020 already mention this in the release notes of 3.11 and 3.12.  Ah, those are also notes for bug fix releases, they were not yet in the first final releases.

Meanwhile locally I see that even the latest Python 3.8 has the "strict" parameter.

So indeed the way to go is not to rely on `getaddresses` working properly, but to have our own extra checks.

**Comment by mauritsvanrees** [comment]
Closing this PR in favour of #4023

**Pull request closed without merging**
