### PR TITLE
Add display_publication_date_in_byline to Site control panel

### PR DESCRIPTION
**Pull request by esteele**
See also: 
* https://github.com/plone/plone.app.layout/pull/58
* https://github.com/plone/plone.app.upgrade/pull/46

Refs plone/Products.CMFPlone#346

### CODE REVIEW

**Comment by djay** [comment]
Isn't the byline switched off for public views? Wouldn't it be confusing to retain this setting if it has no effect on the theme? see discussion in #741 and the issues it replaces

**Comment by vangheem** [comment]
@djay the byline viewlet code is still there. That is what @esteele is updating.

What is the status of byline anyways? Did it ever get re-added. Or did we decide on a compromise. It looks like the viewlet class is still there so we just have to add the zcml include back in?

**Comment by djay** [comment]
@vangheem personally I think the byline as it has been done traditionally is a bit weird. It served two functions. one for the public should your theme require it. Another for editing/admin purposes for logged in users. Thats why it has this toggle mode to determine if its public or just for logged in users. We no longer need it for logged in users as the toolbar replaces it.
For the public hector makes the argument that many sites use this, but I think really just for certain content types like forum posts, blog posts or news posts. But we implement as all or nothing across the board. So you’d have to do fancy diazo to restrict it down to just the content types you want.
Some sites do have a generic public “page last modified on” but they are not that common anymore I think. 

Another alternative is a type specific mechanism to add a byline, and one thats within the themers control. 
Maybe a byline behaviour enabled by default for news types that has some specific rules in the barceloneta theme.
But that still makes and extra step for someone to make a generic theme. I still think its really a theme choice as to if you want to display that information to the public or not. Same as having a footer or a search bar or a hit counter. But others seem to disagree with me on this. So no clear decision. 
BTW a theme implemented byline would be something in barceloneta that uses theme TAL expressions. I’m not even sure you can put theme TAL expressions in a manifest.cfg right?

**Comment by hvelarde** [comment]
@djay this has to be reverted as it was removed without consensus; we can talk about it later, but we need the standard behavior back in Plone 5 final.

**Pull request merged**
