### PR TITLE
Restore the possibility to sort catalog query results with multiple indexes [5.1.x]

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by ale-rt** [comment]
Test failure looks unrelated: https://jenkins.plone.org/job/pull-request-5.1/1663/testReport/junit/Products.CMFPlone.tests.test_robot/RobotTestCase/Scenario_A_page_is_opened_to_edit_in_TinyMCE/
I am restarting the PR job: https://jenkins.plone.org/job/pull-request-5.1/1664/

**Comment by ale-rt** [comment]
@jensens given you merged #2648 do you mind checking this one also?

**Comment by jensens** [comment]
@ale-rt i would say, just merge if green!

**Comment by jensens** [comment]
or greenish.... ;)

**Comment by ale-rt** [comment]
Relevant PR is green https://jenkins.plone.org/job/pull-request-5.1/1664/ but I cannot merge without an approval:
image

**Comment by jensens** [comment]
done

**Comment by ale-rt** [comment]
Thanks!

**Pull request merged**
