### PR TITLE
Recompile resources

### PR DESCRIPTION
**Pull request by frapell**
New compilation for plone and plone-logged-in bundles. This includes latest changes to mockup, including the column sorting in folder_contents

This PR should be merged instead of https://github.com/plone/Products.CMFPlone/pull/2461

### CODE REVIEW

**Comment by frapell** [comment]
Upgrade steps in https://github.com/plone/plone.app.upgrade/pull/168

**Comment by frapell** [comment]
PR for 5.2 https://github.com/plone/Products.CMFPlone/pull/2472

**Comment by petschki** [comment]
since this resources also contain the fix for #2461 is this too late for 5.1.3 ? 
@esteele @jensens

**Comment by jensens** [comment]
@petschki IMO we need the fix for https://github.com/plone/Products.CMFPlone/pull/2461 in 5.1.3 - but I am not in the @plone/release-team to decide it

**Comment by petschki** [comment]
hm ... my question is answered by looking at CHANGES.txt ... 5.1.3 released on 2018-06-22 ...https://github.com/plone/Products.CMFPlone/blob/5.1.x/CHANGES.rst#513-2018-06-22 so lets pull everything into 5.1.4 💪🏼

**Comment by petschki** [comment]
@plone/release-team since this pull request fixes #2461 (folder_contents issue) and Plone 5.1.3 release is still pending, could this be released as 5.1.3.1 ?

**Comment by thet** [comment]
@esteele please consider re-packaging Products.CMFPlone and plone.app.upgrades for the 5.1.3 release!

**Pull request merged**
