### PR TITLE
Plip 1483 retina image scales

### PR DESCRIPTION
**Pull request by didrix**
https://github.com/plone/Products.CMFPlone/issues/1483

### CODE REVIEW

**Comment by ebrehault** [comment]
Tests are passing. The code looks ok.
Of course, the `getObject` thing is not ideal but we have no choice I guess.
@thet, any comment? (as you offered to review this PLIP)

**Comment by mauritsvanrees** [comment]
We might want to introduce a catalog metadata column: boolean `has_image` which is True when at least one image field is filled in, or `images` with a list of image field names that have a filled in image. Plus a smart enough indexer to fill this. But that seems something for a different PLIP, out of scope for this one.

**Comment by ebrehault** [comment]
@mauritsvanrees we already have the `getIcon` index, and @didrix still uses it in his modified templates. The only difference is now we have to wake up the objects to get the img tag (but we only do that when we know there is an image, so that's ok I guess).

**Comment by jensens** [comment]
Ok, the current ``@@images``  implementation is kind of limited here. ``getObject`` is usually not what we want. I don't think I will give a +1 for the PLIP as long this is not solved.

So we need to know primary the current UIDs of the image scales. The ``plone.scale`` implementation already attaches this info to the object. Question is, if we may provide an central infrastructure where this is cached, so we can prevent waking up the object. I'd say, Yes:

The ``@@images`` may then adapt the brain itself and wake up the object only if there is no cached information.

There is nothing more needed than ramcache/alternative memcached mapping:
``object-UID+cachekey(height, width, scale, **otherkw) -> fieldname/Scale UID``.

I can help implementing this, its not that difficult, because the bits and pieces are already around.

**Comment by ebrehault** [comment]
@jensens, I agree waking up objects in the advanced search template is quite bad (on the 2 others, I think it is probably harmless), but yes sure, if you think we can avoid it easily, that would be ideal!

**Pull request merged**
