### PR TITLE
undo icontentish interface in 6.0.x 

### PR DESCRIPTION
**Pull request by Akshat2Jain**
this pr is related to #3836

### CODE REVIEW

**Comment by Akshat2Jain** [comment]
@wesleybl

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by Akshat2Jain** [comment]
@wesleybl some test are still failing

**Comment by davisagli** [comment]
@Akshat2Jain @wesleybl I think this is probably too big a change to make for Plone 6.0, since it was already released some time ago. If someone is depending on the fact that the Plone site does not provide the IContentish interface, then it is a breaking change. So, I would keep it for Plone 6.1 only and not do this backport.

**Pull request closed without merging**
