### PR TITLE
Add email from address validation in mail controlpanel

### PR DESCRIPTION
**Pull request by uwaiszaki**

### CODE REVIEW

**Comment by uwaiszaki** [comment]
@mauritsvanrees  One Jenkins test is giving an error and others are not completed yet, Can u please tell me what the problem is so that i can fix this.

**Comment by mauritsvanrees** [comment]
The Jenkins errors on 5.1 seem a temporary glitch. I have restarted that one. Let's see how that one goes.

On 5.2 there was an unrelated error in the buildout. But actually no tests should be run on 5.2, because this is a PR for the 5.1.x branch.

**Comment by mauritsvanrees** [comment]
On 5.1 the same five tests fail [now](https://jenkins.plone.org/job/pull-request-5.1/1715/) as [before](https://jenkins.plone.org/job/pull-request-5.1/1702/):

- plone.app.testing.helpers.rst
- plone.app.testing.layers.rst
- plone.testing.z2.rst
- plone.app.z3cform.tests.test_widgets.RelatedItemsWidgetTests.test_multiple_selection
- plone.app.z3cform.tests.test_widgets.RelatedItemsWidgetTests.test_single_selection

But the same tests fail in [Jenkins job 1713](https://jenkins.plone.org/job/pull-request-5.1/1713/), which is in a totally different package.
@plone/testing-team Is this a known issue, these five sometimes failing tests on PRs for 5.1?

I have immediately started [another test run](https://jenkins.plone.org/job/pull-request-5.1/1716/). Let's see.

**Comment by mauritsvanrees** [comment]
@uwaiszaki Ah, when I checkout your branch locally, and run `bin/test -s plone.app.testing -t helpers.rst`, which is one of the failing tests, then it fails for me too.

It seems that your branch is slightly outdated. If you merge or rebase on the latests 5.1.x branch of CMFPlone, I suspect that the tests will pass.

**Pull request closed without merging**
