### PR TITLE
Cleanup patterns settings

### PR DESCRIPTION
**Pull request by thet**
This PR removes the "After the deadline" plugin, which is dead code.
It removes the relevant code parts without a deprecation warning, which is probably not acceptable.
How should I proceed here? Deprecate it for 6.0 and let it be removed for 6.1? Or should this breaking change to into 7.0?

It's not an urgent issue but would remove some code which is most probably unused. 

Together:
https://github.com/plone/Products.CMFPlone/pull/3765
https://github.com/plone/plone.base/pull/33
~~https://github.com/plone/plone.api/pull/504~~ merged
https://github.com/plone/plone.app.upgrade/pull/328

Jenkins:
https://jenkins.plone.org/job/pull-request-6.1-3.11/156/

### CODE REVIEW

**Comment by thet** [comment]
PR: https://jenkins.plone.org/job/pull-request-6.0-3.11/488/

**Review by petschki — APPROVED** [review]

**Comment by thet** [comment]
> Does it need an upgrade step to remove existing entries from registry?
I think so. I added this to the [Buschenschanksprint project page](https://github.com/orgs/plone/projects/44). Would be an easy task to do there.

**Comment by reinhardt** [comment]
> > Does it need an upgrade step to remove existing entries from registry?
> 
> I think so. I added this to the [Buschenschanksprint project page](https://github.com/orgs/plone/projects/44). Would be an easy task to do there.

I'll look into it.

**Review by mauritsvanrees — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
Tests failed due to changes missing from master.  I did a rebase and will restart the jobs.

**Comment by mauritsvanrees** [comment]
All green, I merge.

**Pull request merged**
