### PR TITLE
Backport filter improvements for URL Management control panel

### PR DESCRIPTION
**Pull request by davisagli**
This backports #4009 and #4031 to the 6.0.x branch.

### CODE REVIEW

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
regarding `testvalidateSingleEmailAddress` ... see this backport: #4033

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Review by sneridagh — APPROVED** [review]
LGTM

**Pull request merged**
