### PR TITLE
Added <hr> tag as a default in Standard Definition of IFilterSchema.

### PR DESCRIPTION
**Pull request by vinay72**
I have added a  <hr> Tag in the Standard Definition of IFilterSchema #2457 .

### CODE REVIEW

**Comment by jensens** [comment]
@vinay72 Why filter `<hr>`?

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
It's allowing ``<hr>``.

**Comment by jensens** [comment]
@vinay72 to get this ready for merge please add a news-file (changelog) and then run the tests again. 

Also, as @thet explained, this needs an upgrade step to get the feature to existing sites and not only new ones.

If both are green @thet or I or someone else will merge.

**Comment by petschki** [comment]
this is superseeded by #3103  ... upgrade steps coming ...

**Pull request closed without merging**
