### PR TITLE
Fix problem when adding a Plone site with a custom INonInstallable ut…

### PR DESCRIPTION
**Pull request by thet**
…ility without a getNonInstallableProfiles method.

Fixes: #3862.

### CODE REVIEW

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
Thanks!

**Comment by mauritsvanrees** [comment]
Errr.... this should have been for the 6.0.x branch, not master. :-)
Let me see if I can edit it.

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
