### PR TITLE
Fix mail_password form

### PR DESCRIPTION
**Pull request by frapell**
This fixes https://github.com/plone/Products.CMFPlone/issues/3008

### CODE REVIEW

**Comment by frapell** [comment]
@jenkins-plone-org please run jobs

**Comment by frapell** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
@frapell Can you rebase and try to merge it?

**Comment by frapell** [comment]
@jenkins-plone-org please run jobs

**Comment by vincentfretin** [comment]
Oh my, 43 commits. Can you use instead
```
git rebase -i master
git push --force
```
?

**Comment by frapell** [comment]
@vincentfretin too many conflicts to fix. I created a new PR in https://github.com/plone/Products.CMFPlone/pull/3133

**Pull request closed without merging**
