### PR TITLE
feat: allow all TinyMCE settings to be set from control panel

### PR DESCRIPTION
**Pull request by Gagaro**
This allows the possibility to set all TinyMCE settings. (There are a lot of things possible: http://www.tinymce.com/wiki.php/Configuration)

This change should need an upgrade step, but I'm not sure how to add it in plone.app.upgrade (if I'd have to create a new profile or if I could use `to_500`)?

So if someone could direct me in the right direction, thanks!

### CODE REVIEW

**Comment by tomgross** [comment]
Cool thanks! In plone.app.upgrade you Need to Register an upgrade step in https://github.com/plone/plone.app.upgrade/blob/master/plone/app/upgrade/v50/configure.zcml with a new handler. Let's say to_501.

A changelog entry and a test would be great.

**Comment by Gagaro** [comment]
Upgrade step added, I'll try to add a test now (changelog entry was already there).

**Comment by Gagaro** [comment]
Test added.

**Comment by tomgross** [comment]
http://jenkins.plone.org/job/pull-request-5.0/431/

**Pull request merged**
