### PR TITLE
Fix950 Missing personal toolbar

### PR DESCRIPTION
**Pull request by ichim-david**
Besides that single issue I've fixed several other which can be seen in the comment.
One fix is for ticket https://github.com/plone/Products.CMFPlone/issues/1002#issuecomment-140805065

### CODE REVIEW

**Comment by ichim-david** [comment]
I'm investing why on my branch
git rebase master
 basically pushed my commits to the top while keeping them where they were as well basically duplicating the work.
I think that the previous commits need to be removed or squashed somehow.

**Comment by hvelarde** [comment]
you need to rebase.

Jenkins job will run here: http://jenkins.plone.org/job/pull-request-5.0/331/

**Comment by ichim-david** [comment]
@hvelarde I will do so in about an hour when I get home from work.

**Comment by ichim-david** [comment]
@hvelarde  I've successfully rebased and got rid of the extra commits that were doubled from my branch but even logged in and clicking on build now will not allow me to run the jenkins build at the link given by you 
http://jenkins.plone.org/job/pull-request-5.0/331/

**Comment by ichim-david** [comment]
Found my way to add a build myself for this pull request.
Waiting for info now from http://jenkins.plone.org/job/pull-request-5.0/335

**Comment by ichim-david** [comment]
Tests passed http://jenkins.plone.org/job/pull-request-5.0/335

**Comment by hvelarde** [comment]
awesome!

**Pull request merged**
