### PR TITLE
upgrade patternslib 2.0.11

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
tests running: http://jenkins.plone.org/job/pull-request-5.0/432/

**Comment by vangheem** [comment]
@jcbrand in the future, we can not merge major mockup changes without the complementary, working CMFPlone integration changes. This is hosing mockup dev master right now.

**Comment by jcbrand** [comment]
@vangheem I understand. I'm not sure what needs to be done to Products.CMFPlone. Is it documented somewhere?

**Comment by jcbrand** [comment]
@vangheem Appears to work now for me locally. Can you please trigger a new build?

**Comment by vangheem** [comment]
tests running again: http://jenkins.plone.org/job/pull-request-5.0/438/

**Comment by vangheem** [comment]
Closing this and starting a new PR.

**Pull request closed without merging**
