### PR TITLE
Add the styles CSS from the theme to the content CSS to load.

### PR DESCRIPTION
**Pull request by Rudd-O**
Without this, the theme creator's styles CSS is never loaded by TinyMCE.  `importcss_file_filter` acts only as a filter lambda "permit these paths to load", but if these paths are not added to the `content_css` setting, then they are never loaded by TinyMCE.

The official Plone theming documentation states this should work — it doesn't without this patch, it does with it.

### CODE REVIEW

**Comment by Rudd-O** [comment]
@jenkins-plone-org please run jobs

**Comment by MrTango** [comment]
Why do you use yoru own fork for the PR? it's much easier to test your PR when it's direktlich a branch inside the original repository ;)

**Comment by MrTango** [comment]
@Rudd-O did you add your CSS in your manifest.cfg tinymce-content-css?

**Comment by Rudd-O** [comment]
> Why do you use yoru own fork for the PR? it's much easier to test your PR when it's direktlich a branch inside the original repository ;)

I completely agree and until today I did not know I could just push to a branch in the org!  Sorry, I am super green in this stuff!

**Comment by Rudd-O** [comment]
> Also we have to make sure that the theme css is not used for the format list in tinymce.

Imma save you some time.  With this PR, if you don't specify `tinymce-styles-css`, the content CSS of the theme (which used to slow down the formats dropdown enormously) *is* applied to the content, but is **not** loaded in the formats dropdown anymore.  Of course, the URL you specify in `tinymce-styles-css` **is** (with this PR) loaded in the formats dropdown.

**Comment by Rudd-O** [comment]
For some reason the merge commit went into my own repo, instead of this one.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by Rudd-O** [comment]
@jenkins-plone-org please run jobs

**Comment by Rudd-O** [comment]
Chex passed @jensens @thet  @MrTango .  Thanks!

**Review by jensens — APPROVED** [review]

**Pull request merged**
