### PR TITLE
Fix social media schema field types

### PR DESCRIPTION
**Pull request by hvelarde**
`twitter_username`, `facebook_app_id` and `facebook_username` should be `ASCIILine` instead of `TextLine`.

refs. https://github.com/plone/plone.app.upgrade/pull/107
refs. https://github.com/plone/plone.app.layout/pull/121

### CODE REVIEW

**Comment by hvelarde** [comment]
giving a second look I think we need to provide an upgrade step to cast those values to `str()`.

**Comment by gforcada** [comment]
Do Twitter, Facebook and so on really only allow ASCII for the username?

If you already check just discard my question, I'm only thinking aloud 😃

**Comment by hvelarde** [comment]
Twitter:
selection_022

Facebook:
selection_023
selection_024

**Comment by hvelarde** [comment]
I need help with this; I don't understand Jenkins and I think failures are not related with my changes.

**Comment by gforcada** [comment]
There seems to be a general problem, see the first error on the console log:

http://jenkins.plone.org/job/pull-request-5.1/1423/consoleFull

**Comment by hvelarde** [comment]
found the issue, thanks!

**Comment by hvelarde** [comment]
@plone/framework-team it's green, guys!

**Pull request merged**
