### PR TITLE
change Security link title to "Security Settings"

### PR DESCRIPTION
**Pull request by tkimnguyen**
to be consistent with the control panel's title and to avoid having a "Security" link inside the "Security" category (seems repetitive)

### CODE REVIEW

**Comment by hvelarde** [comment]
unfortunately this needs an upgrade step.

**Comment by jensens** [comment]
@tkimnguyen may you add an upgrade step in ``plone.app.upgrade`` to get this ready?

**Comment by tkimnguyen** [comment]
ok I will

**Comment by jensens** [comment]
Any plans to finish this one? I not, please close the PR.

**Comment by vincentfretin** [comment]
2 years without progress, I close. Please reopen if you want to continue this.

**Pull request closed without merging**
