### PR TITLE
Make plone.restapi a depedency of CMFPlone.

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
http://jenkins.plone.org/view/All/job/pull-request-5.2/157/

**Comment by gforcada** [comment]
@tisto shouldn't that be merged to master rather 5.1?

**Comment by tisto** [comment]
@gforcada to be honest, I have no idea. master branch is outdated and I have no idea what status Plone 5.2 is in right now.

**Comment by mauritsvanrees** [comment]
This is a PLIP for Plone 5.2, right? So it should be on CMFPlone master.
What do you mean with 'master branch is outdated'? I see only one thing missing compared to the CMFPlone 5.1 branch, and that is a mockup update (PR ##2257). Do you mean that?

**Comment by tisto** [comment]
@mauritsvanrees I got some strange conflicts when trying to merge into master, so I assumed I used the wrong branch or master is not used/outdated. Will give it another try tomorrow and report back...

**Pull request closed without merging**
