### PR TITLE
move hero to content

### PR DESCRIPTION
**Pull request by gyst**
fixes https://github.com/plone/Products.CMFPlone/issues/974
only together with https://github.com/plone/plonetheme.barceloneta/pull/83

### CODE REVIEW

**Comment by thet** [comment]
It would be awesome to have a ``hero`` format selection class for TinyMCE too! This setting has to be added to the registry.

Provided, this approach found consensus. But it's even translatable, isn't it? (that was @esteele objection in the original discussion)

**Comment by gyst** [comment]
Yes it's translatable. And the corresponding barceloneta PR anticipates TinyMCE support in two ways:
- The actual styling classes are part of the theme. The content only has to flag a block '.hero'.
- The hero is supported on any page and auto-removes its boilerplate when not used on a page.

**Comment by pbauer** [comment]
@thet the whole ``plone-frontpage.pt`` is translated and its content is set as the content of the fontpage in the target-language in https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/setuphandlers.py#L174-L195 The code is somewhat crazy but it works.

**Comment by djay** [comment]
@gyst One enhancement would be allow it to be either in a portlet or in the main content. It might complicate the diazo but the advantage is that provides a way for the user to have a hero on a whole subsection of their site if they want. That would require documentation somewhere however.

I think its worth making the Hero style appear in the tinymce format menu. If the user removes the hero element they would have no way to add it back without directly editing the html.

**Comment by gyst** [comment]
@djay The diazo rules I wrote should also support a hero in a portlet. They just take any '.hero' content anywhere and plunk it into the '#hero' slot above.

**Comment by thet** [comment]
@gyst what @djay said about the diazo class in TinyMCE format menu is what I meant. You have to add this as an registry.xml entry.

**Comment by jensens** [comment]
@gyst thank for caring! I reviewed it a bit:

- rebase is needed here.
- do we need an upgrade step? I dont think so, but I'am not sure.
- do we need to update docs? (if so please create a ticket at plone/documentation)
- do we need to update translations? (if so please create a ticket at collective/plone.app.locales)

This can be merged w/o TinyMCE changes. Would be cool to have them anyway.

This has to be merged with plone/plonetheme.barceloneta#83 (note to self)

**Comment by gyst** [comment]
Hi @jensens 
- Rebase is needed here. Done.
- Do we need an upgrade step? No. The only effect on existing sites is that it removes the hero from an old front-page, in case you had not removed it already. That's a feature, not a bug, see community discussion. 
- Do we need to update docs? No. This makes it possible to remove the hero from the editor in an obvious way. Adding a hero should not be documented but enabled in TinyMCE.
- Do we need to update translations? Yes. https://github.com/collective/plone.app.locales/issues/102

**Pull request merged**
