### PR TITLE
Fix toolbar word break

### PR DESCRIPTION
**Pull request by tmassman**
Fix wrong CSS and recompile plone resources.

### CODE REVIEW

**Comment by thet** [comment]
Refs:
- https://github.com/plone/Products.CMFPlone/pull/2202
- https://github.com/plone/Products.CMFPlone/issues/2315
- https://github.com/plone/Products.CMFPlone/issues/2315

@zopyx @jensens this is done due to poor browser support for the ``hyphen`` property - see: https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#Browser_compatibility
It also didn't work properly in the browsers we tested - right @tmassman ?

If there is any disagreement - let's discuss it.

**Comment by tmassman** [comment]
Yes, `word-wrap` is the only reliable property we can use here. Thx for the merge!

**Comment by zopyx** [comment]
Hyphenation is supported on latest Firefox and Chrome versions on Mac and Windows (Linux support only fire FF), supported by Safari, supported by iOS. And hyphens: auto does not hurt if it is not supported.

**Comment by thet** [comment]
@zopyx done with:
https://github.com/plone/Products.CMFPlone/commit/3700a62852d75632545ba6c0d1d222df6a86f5f1
updated in:
https://github.com/plone/Products.CMFPlone/pull/2546

bundle compilation on both 5.1 and 5.2 will be done soon.

**Pull request merged**
