### PR TITLE
update HTMLFilter defaults to enable TinyMCE layout features [master]

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
seems that `master` is not beeing validated by jenkins?

**Comment by ale-rt** [comment]
Hi @petschki there is no automatic trigger for master yet.
You have to:
1. go to https://jenkins.plone.org/
2. log in
3. Go to https://jenkins.plone.org/job/pull-request-6.0-3.8/build?delay=0sec
4. Copy the PR link (or links): in this case https://github.com/plone/Products.CMFPlone/pull/3104
5. Start the build

You can do that for Python 3.6, 3.7 and 3.8.
I already did that for 3.8, I will let you practice with it and try to start the build for 3.6 and 3.7 ;)

**Comment by ale-rt** [comment]
BTW @plone/testing-team is it possible to have this triggered by default?

**Comment by petschki** [comment]
@ale-rt done ...

**Comment by ale-rt** [comment]
Thanks, I will try to have a look at the open PRs soon!

**Pull request merged**
