### PR TITLE
Implementation for PLIP 1342 portal actions

### PR DESCRIPTION
**Pull request by ebrehault**
See #1342

@vangheem if you want to review it, here is the buildout:
https://github.com/plone/buildout.coredev/blob/5.0/plips/plip-1342-portal-actions.cfg

### CODE REVIEW

**Comment by gforcada** [comment]
@ebrehault I just created this PLIP job so that you can run it as many times as you wish:

http://jenkins.plone.org/view/PLIPs/job/plip-1342-portal-actions/

**Comment by ebrehault** [comment]
thank you :)

**Comment by ebrehault** [comment]
@gforcada could you tell me if there anything wrong with my PLIP buildout https://github.com/plone/buildout.coredev/blob/5.0/plips/plip-1342-portal-actions.cfg
because I get a very strange error in Jenkins http://jenkins.plone.org/view/PLIPs/job/plip-1342-portal-actions/1/console
(it looks like if plone.portlets is not in the path, and the PLIP is not related to plone.portlets, it is not in the checkouts or anything...)

Note: is it mandatory to extends jenkins.cfg ? (I see that some PLIP buildout extends it, some don't)

**Comment by gforcada** [comment]
@ebrehault I think that jenkins.cfg should not be extended... 

As for debugging why plone.portlets is not there, you can always run buildout annotate on the plip cfg file and check the output.

It's definitely something weird :-/

**Comment by ebrehault** [comment]
Tests are ok: http://jenkins.plone.org/view/PLIPs/job/plip-1342-portal-actions/2/

**Pull request merged**
