### PR TITLE
Recompile plone bundles fixing #2512

### PR DESCRIPTION
**Pull request by sunew**
after https://github.com/plone/mockup/pull/863, fixing https://github.com/plone/Products.CMFPlone/issues/2512

### CODE REVIEW

**Comment by frapell** [comment]
@sunew First, https://github.com/plone/mockup/pull/863 should be merged to master, and then you can bring in the "latest mockup master" into CMFPlone.

Doing it like this, means that work is done with https://github.com/plone/mockup/pull/863 which we do not know yet, and also we could be missing stuff from master that has been merged already...

**Comment by sunew** [comment]
@frapell agreed

**Comment by jensens** [comment]
@sunew which are the packages belonging together in one merge? this one and https://github.com/plone/plone.app.upgrade/pull/171 ?

**Comment by jensens** [comment]
also, we need the same for master?

**Comment by sunew** [comment]
@jensens yes. comming up

**Comment by sunew** [comment]
@jensens 

> which are the packages belonging together in one merge? this one and plone/plone.app.upgrade#171 ?

yes 
mockup has been merged already

**Pull request merged**
