### PR TITLE
move colphon and footer out of skins

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
tests: http://jenkins.plone.org/job/pull-request-5.0/258/

**Comment by vangheem** [comment]
This still works with the classic portlet that plone is using for the footer right now.

**Comment by vangheem** [comment]
Tests pass. @esteele this what you were looking for?

**Comment by esteele** [comment]
@vangheem: Perfect. Thank you.

**Comment by vangheem** [comment]
@esteele this is rebased if you want to merge.

**Pull request merged**
