### PR TITLE
No longer provide deprecated secureSend method for MailHost.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Removed our patch that added `secureSend` to the `MailHost`.
This was originally scheduled for removal in Plone 5.0.
See issue #965

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Test failure in `Products.CMFPlone.tests.testSecurity.TestAttackVectorsFunctional.test_widget_traversal_1` and `test_widget_traversal_2` which should have nothing to do with this pull request. Strangely, I get the same failures on locally on master, though the 5.1 Jenkins tests are happy.
Well, let's try again.

**Comment by jensens** [comment]
Strange, this failure.

**Comment by gforcada** [comment]
I rebased the branch and started the job again, let's see if it works now

**Comment by mauritsvanrees** [comment]
Due to some subtlety in the order of imports and package loading, we need to load `Products.CMFPlone.patches` earlier. The important thing is that our patch for `ClassDirective.require` in `security.py` is loaded early. This is related to today's hotfix, and is influenced by the removal of the securemailhost patch. So I have put them in one pull request.

**Pull request merged**
