### PR TITLE
Make contact form extensible. 

### PR DESCRIPTION
**Pull request by tisto**
This fixes https://github.com/plone/Products.CMFPlone/issues/1879.

### CODE REVIEW

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.1/1127/

**Comment by davisagli** [comment]
@tisto tests are failing with "The class deriving from AutoExtensibleForm must have a 'schema' property". you probably just need to change the `fields =` line.

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.1/1129/

**Comment by tisto** [comment]
Jenkins job is green now.

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.1/1130/

**Comment by tisto** [comment]
Jenkins job is green. Please review and merge.

**Comment by davisagli** [comment]
Hurray!

**Pull request merged**
