### PR TITLE
Adding a before publishing traverse to avoid the default view on REST calls.

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.0/83/

**Comment by tisto** [comment]
Build is green. cc @bloodbare

**Comment by jensens** [comment]
btw., why is a subscriber to ``zope.traversing.interfaces.IBeforeTraverseEvent`` not sufficient?

**Comment by fulv** [comment]
Why does this have the 5.0 milestone?  Doesn't seem like a blocker.

**Comment by jensens** [comment]
@fulv indeed, I removed it

**Comment by jensens** [comment]
i close this one, if still needed feel free to reopen.

**Pull request closed without merging**
