### PR TITLE
Creating a document called 'layout' breaks the parent folder

### PR DESCRIPTION
**Pull request by erral**
See the bug report #1931

### CODE REVIEW

**Comment by erral** [comment]
The Jenkins build here is expected to fail

**Comment by sunew** [comment]
@erral So what would be the solution? Making 'layout' a 'reserved word' (making users unable to use it as id), or adding something to the (from title generated) id ("layout_" or similar) ?

("layout" is the zope property used for setting a view for an object)

**Comment by sunew** [comment]
yes and the tools too

**Comment by davisagli** [comment]
Hmm, I thought this check was done by the check_id script https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_scripts/check_id.py but it already includes `layout` in a list of reserved names so I wonder why that's not working.

**Comment by erral** [comment]
The check_id script is also called when renaming a content object through the actions menu or folder_contents.

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
