### PR TITLE
Rework addsite language selection

### PR DESCRIPTION
**Pull request by jaroel**
It shows all support country specific languages grouped by language.

screen shot 2015-07-16 at 20 25 46

### CODE REVIEW

**Comment by jaroel** [comment]
See #411 too.

**Comment by jensens** [comment]
test http://jenkins.plone.org/job/pull-request-5.0/117/

**Comment by jaroel** [comment]
Looks like it doesn't test the changes?

**Comment by jaroel** [comment]
My bad, it does.

**Comment by jaroel** [comment]
A rebase fixed the toolbar_position error.
New test run: http://jenkins.plone.org/job/pull-request-5.0/123/

**Pull request merged**
