### PR TITLE
Fixup explicitacquisition

### PR DESCRIPTION
**Pull request by jaroel**
We need to explicitly set the SKIP_PTA flag as it is set on module load.

### CODE REVIEW

**Comment by jaroel** [comment]
@jenkins-plone-org please run jobs

**Comment by jaroel** [comment]
@jenkins-plone-org please run jobs

**Comment by jaroel** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — COMMENTED** [review]
Looks okay at first glance, but the tests fail:

```
Failure in test test_portal_foo_acquired (plone.rest.tests.test_explicitacquisition.TestExplicitAcquisition.test_portal_foo_acquired)
Traceback (most recent call last):
  File "/srv/python3.11/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/srv/python3.11/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/srv/python3.11/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
  File "/home/jenkins/workspace/pull-request-6.1-3.11/src/plone.rest/src/plone/rest/tests/test_explicitacquisition.py", line 56, in test_portal_foo_acquired
    with self.assertRaises(NotFound):
  File "/srv/python3.11/lib/python3.11/unittest/case.py", line 262, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
  File "/srv/python3.11/lib/python3.11/unittest/case.py", line 199, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: NotFound not raised
```

**Comment by jaroel** [comment]
I think this is because we don't have the plone.rest branch checked out.
https://jenkins.plone.org/job/pull-request-6.1-3.11/308/ should run with both, and the plone.rest build is green.

**Review by mauritsvanrees — APPROVED** [review]

**Review by mauritsvanrees — APPROVED** [review]
LGTM.  Running some jobs now.  Can be merged when green, and when https://github.com/plone/plone.rest/pull/166 is green.

In both PRs the failing changelog test can be ignored: these PRs are fixups for earlier changes that have not been released yet and that *do* have a changelog entry.

**Pull request merged**
