### PR TITLE
Added tests for add-ons control panel. [5.2]

### PR DESCRIPTION
**Pull request by mauritsvanrees**
And two very minor fixes:
- Add a link to the Site Setup.
- Let `get_product_version` work when you call it with `CMFPlacefulWorkflow` too.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@gforcada I tried two times on Jenkins 5.2 PR, but all robot tests are failing:

```
WebDriverException:
Message: Can't load the profile. Profile Dir: /tmp/tmpVfL_Bb/webdriver-py-profilecopy
If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

Did you install `geckodriver` (or `chromedriver`) on Jenkins maybe, or did something else that could cause this as side effect?  The normal 5.2 Robot test job (so not the PR job) goes just fine.

**Comment by gforcada** [comment]
@mauritsvanrees yes, sorry, I did install the gecko driver and updated firefox to version 58, but as selenium is old it does not work. On the pull request to test the newer KGS for p.a.robotframework (https://github.com/plone/buildout.coredev/pull/407) it hangs at some point :-/

I will revert the firefox version bump until we can try to fix the errors.

**Comment by mauritsvanrees** [comment]
No problem. I can see it is tricky test a new KGS with new Firefox and still keep the old tests running.
I reran the job and got different errors. I'll open a different issue.

**Comment by mauritsvanrees** [comment]
Green! :-)

**Pull request merged**
