### PR TITLE
Correct formTabs-links, fixes #1640.

### LINKED ISSUE #1640: form_tabbing.js doesn't regard hashes in URL
Calling an edit-form with an URL containing a hash, like `front-page/edit#fieldset-dates` one still lands on the default-tab open, not the dates-tab. The fix is to change the line:

`var targetPane = item.find('.enableFormTabbing input[name="fieldset"]').val() || window.location.hash;`

To:

`var targetPane = window.location.hash || item.find('.enableFormTabbing input[name="fieldset"]').val();`

So a hash-URL preceeds the default-selected tab.

Adding this as an issue instead of a PR, because I'm not sure how the procedure is for Plone-4.3 fixes.

### PR DESCRIPTION
**Pull request by ida**

### CODE REVIEW

**Comment by ida** [comment]
@davilima6 Ended up deleting and cloning again a fork :) Closed old PR and opened this one, now.

**Comment by davilima6** [comment]
Excellent, thank you. Lgtm but I'll wait for another member to review and merge.

**Comment by ida** [comment]
Awesome! Sorry for the direct commits in CHANGES, thought I was in my fork. Didn't dare to rewrite history there, though.

**Comment by davilima6** [comment]
Np, just please never rewrite or `push -f` for any reason :) Lastly, next time it should be better if you work in a branch instead of a fork. You can create one with `git checkout -b my_feature_branch`.

**Comment by jensens** [comment]
LGTM too

**Comment by ida** [comment]
@davilima6 @jensens Never been reviewed twice, what a luxury ;) Much appreciated, thanks for your time and tremendous contributions!

**Comment by davilima6** [comment]
You're welcome, @ida! Let's have more of these ;)

**Comment by ida** [comment]
PS: I intially used the GitHub-web-UI-editor, which seemed to be a good choice, concerning it was just about changing two lines in one file. The hurdles though I (and as I read, a lot of other people, too) experienced then, were:

- One cannot edit several files at once, so each file-modification creates an own commit-msg, which doesn't allow to sum them up in one commit.

- Ok, so let's use a fork. I already had one, let's update/sync it with the upstream branch, should be easy, found out it's not. So finally I deleted the fork and got a fresh one, which...

- ... takes quite some time.

I summed this up, to explain in detail what can be hurdles for people contributing more easily, especially e.g. for translators. I think, contributing translations shouldn't require in-depth knowledge about dev-workflows.

My suggestion would be, to either be tolerant about having several commit-msg instead of one for those cases, so using the web-UI can be possible, or let reviewers squash the msgs for them. For the latter I'd be absolutely willing to be around to help.

Does that sound feasible to you?

Regards, Ida

**Comment by jensens** [comment]
As long as all commits are on the same branch and resulting in one PR this is fine. Github offers squash-merges, so several commits can be merged easily into one while merging.

**Comment by ida** [comment]
@jensens Ah, very nice, I didn't see that option, thanks for the quick reply! Hope to find some time soon, to update the docs about contibuting via web-UI.

**Comment by jensens** [comment]
@Ida btw.: updating with upstream master - on a fork or branch - is relatively easy. On command line its a ``git rebase master``. If it comes to conflicts things may get difficult, so this is not an option for people not deep into git.

I tend to teach non-dev people to use [gitkraken](https://www.gitkraken.com/) which has some icons to click on to get those things done. It offers also useful conflict resolutions. This is feasible even for designers and translators and takes teaching 10-20 minutes face to face or over a Teamviewer/Skype session.

**Pull request merged**
