### PR TITLE
WIP: Rename the global `define` function, plip #1529

### PR DESCRIPTION
**Pull request by vangheem**
To implement plip: https://github.com/plone/Products.CMFPlone/issues/1529

### CODE REVIEW

**Comment by rnixx** [comment]
You simply reset global define AFTER ALL registered resource bundles have been delivered, right?
But then it does not solve our basic problem.

E.g.

https://github.com/collective/collective.js.datatables/blob/master/collective/js/datatables/profiles/plone5/registry.xml <- the JS is delivered as bundle as well...

So to make it work right now we implemented a really bad hack -> https://github.com/collective/collective.js.datatables/blob/master/collective/js/datatables/resources/media/js/jquery.dataTables.min.js#L5

define and require gets unset before the actual script is loaded and then reset to the original values.

That's why I was suggesting to implement a (generated) wrapper around each bundle if desired (except the basic JS, after which define and require gets reset) as described here -> https://github.com/plone/Products.CMFPlone/issues/1529#issuecomment-210304757

Or do I miss something in your approach?

**Comment by rnixx** [comment]
So in order to achieve the flexibility with bundles, merged in one file or not, delivered JS structure may look somthing like:

// plone bundle
* jquery as is
* requirejs as is

// reset define and require

    plone_define = define;
    plone_require = require;

// iterate registered bundle resources

    (function(define, require) { // generated wrapper if defined for bundle in registry (default true)
      require([
        'mockup-pattern-autotoc'
      ], function(AutoTOC){
        // something
      });
    })(plone_define, plone_require); // generated wrapper

    // if no generated wrapper deliver JS as is

// all bundles delivered with addons
...

**Comment by vangheem** [comment]
datatables is a unique case where the packaging is exceptionally difficult and not compatible. If you're packaging inside a bundle with requirejs, there is nothing else, no magic, we can do. Some js packages just suck to work with in packaging.

This PR is only to help those that have trouble including js from manual `<script>` tags or from inside their theme for example.

**Comment by vangheem** [comment]
tests: http://jenkins.plone.org/job/pull-request-5.1/754/

**Comment by vangheem** [comment]
This doesn't always work quite as expected as it can mess with other bundling in other unexpected ways.

I'm putting this PR on hold for now until we can figure out if there is a more safe way.

**Pull request closed without merging**
