### PR TITLE
Add action icon_expr for view/edit Plone Site

### LINKED ISSUE #3327: DX-Site-Root missing icons for view/edit action
The new Icon-Resolver looks for icons in `icon_expr` of the type actions

### PR DESCRIPTION
**Pull request by petschki**
fixes #3327

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
Thanks.
I guess this needs some code in `plone.app.upgrade`, right?

**Comment by petschki** [comment]
@mauritsvanrees can I bump metadata version to 6002 directly on master?

**Comment by mauritsvanrees** [comment]
No. I already bumped the version to 6001 in commit af012be468b00b6214b0155856399385f8bbd094, and there has not been a release since then. So the upgrade step should be for 6001.

People who use the master branch in production will miss the upgrade step, but they should know that already, and know how to work around it in their database: in portal_setup run a small previous upgrade step of CMFPlone to get it to version 6000. Then apply `@@plone-upgrade`.

**Pull request merged**
