### PR TITLE
Implement resource bundle depends on `all` to be rendered at last (6.0 branch)

### PR DESCRIPTION
**Pull request by thet**
Plone 6.0 backport of https://github.com/plone/Products.CMFPlone/pull/4076

### CODE REVIEW

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Review by petschki — APPROVED** [review]

**Comment by stevepiercy** [comment]
Just to confirm, for `all`, we documented that they will appear in the order declared, but here they will appear in alphabetic order. Should I change the docs accordingly?

https://github.com/plone/documentation/pull/1802/files#diff-eab566b0dcb958909e31d49af95b85b45c6197064b0afb537726cd61e467e2e7R106

**Comment by petschki** [comment]
> Just to confirm, for `all`, we documented that they will appear in the order declared, but here they will appear in alphabetic order. Should I change the docs accordingly?
> 
> https://github.com/plone/documentation/pull/1802/files#diff-eab566b0dcb958909e31d49af95b85b45c6197064b0afb537726cd61e467e2e7R106

ResourceRegistry always sorts the bundles alphabetically, so they will appear in the alphabetically order no matter when you declare them ...

**Comment by thet** [comment]
> > Just to confirm, for `all`, we documented that they will appear in the order declared, but here they will appear in alphabetic order. Should I change the docs accordingly?
> > https://github.com/plone/documentation/pull/1802/files#diff-eab566b0dcb958909e31d49af95b85b45c6197064b0afb537726cd61e467e2e7R106
> 
> ResourceRegistry always sorts the bundles alphabetically, so they will appear in alphabetically order no matter when you declare them ...

@stevepiercy my assumption was that the resource registry doesn't do alphabetical sorting, therefore several references in comments and docs that it does sort as added. But that was apparently wrong. I fixed it in this PR.
Thanks for fixing it in the docs!

**Pull request merged**
