### PR TITLE
Use formautofocus pattern.

### PR DESCRIPTION
**Pull request by timitos**
After pull request for plone/mockup#564 is merged. This change will make the autofocus work again.

### CODE REVIEW

**Comment by vangheem** [comment]
testing: http://jenkins.plone.org/job/pull-request-5.0/479/

**Comment by vangheem** [comment]
@gforcada @tisto any idea what is going on? Failed immediately and no error output.

**Comment by timitos** [comment]
It looks like the '/' in the branch name caused the problem. Should i maybe rename the branch and create an new pull request?

**Comment by gforcada** [comment]
@timitos is right, the problem is on the regular expression we use to update the branch... if you don't mind renaming it (dashes are fine and used by other contributors).

We can also update the sed expression to use something else, a # for example.

**Comment by timitos** [comment]
New Pull Request #1205

**Pull request closed without merging**
