### PR TITLE
Set the status of an exception view according to the exception type.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
For Plone 5.2.
Fixes https://github.com/plone/Products.CMFPlone/issues/2187.

### CODE REVIEW

**Comment by jensens** [comment]
Great! We may want to backport this to 5.1 as well, right?

**Comment by mauritsvanrees** [comment]
No, this should not be backported to 5.1: the exception view stuff is Zope 4, so not available in Plone 5.1. The `browser/exceptions.py` file is not there.

**Comment by jensens** [comment]
Hmm, ok. This is confusing, I was the opinion it was not set in subrequest, but now I see the difference.

**Comment by pbauer** [comment]
Looks good. The failing robot test in http://jenkins.plone.org/job/pull-request-5.2/41/testReport/junit/Products.CMFPlone.tests.test_robot/RobotTestCase/Scenario_Allow_comments_for_Link_Type/ should be unrelated.

**Comment by davisagli** [comment]
Hmm. I'm confused why this is necessary, because Zope already does it when it renders an exception view: https://github.com/zopefoundation/Zope/blob/master/src/ZPublisher/WSGIPublisher.py#L108

Maybe the subrequest is wiping that out?

**Comment by jensens** [comment]
Probably b/c subrequest does call own mapply, not calling all of the publisher.

**Pull request merged**
