### PR TITLE
Add markdown extension settings to markup control panel.

### PR DESCRIPTION
**Pull request by thomasmassmann**
Adds enabled markdown extensions for markup portal transform module to markup controlpanel.

The required changes in Products.PortalTransforms will be applied in https://github.com/plone/Products.PortalTransforms/pull/30.

Needs PR:
https://github.com/plone/plone.app.upgrade/pull/229
https://github.com/plone/Products.PortalTransforms/pull/30

### CODE REVIEW

**Comment by thomasmassmann** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
This also need an upgrade step in plone.app.upgrade.

**Comment by thomasmassmann** [comment]
> eventually I'd change the default in `allowed_types` from `default=('text/html', 'text/x-web-textile')` to `default=('text/html', 'text/x-web-textile', 'text/x-web-markdown')`. Is textile even used or working at all (#2991)?

I would do this once there is a markdown editor available to be used. I'm currently evaluating https://ui.toast.com/tui-editor/, but the plugins have to match (what you see in the preview and what Python-Markdown is rendering).

**Comment by thet** [comment]
I think the point of markdown is not to need to use an editor.

However, having an editor available would be nice. But that's a lot more effort.

**Comment by jensens** [comment]
I would add plain markdown to the list as @thet suggested. And merge this PR.
All further changes can go in a second PR.

OT here: Btw. I never used Textile. Removing this in favour of markdown sounds reasonable, given textile is broken anyway. OTOH this is a breaking change, so maybe we should do the removal for Plone 6?

**Comment by thomasmassmann** [comment]
Closes #3076.

**Pull request merged**
