### PR TITLE
fixes 3223. Site Administrator role

### PR DESCRIPTION
**Pull request by ewohnlich**
Fixes https://github.com/plone/Products.CMFPlone/issues/3223

Is there documentation on how to run tests locally for this package? I am just relying on the CI for now

### CODE REVIEW

**Comment by wesleybl** [comment]
To run the tests locally, you must use https://github.com/plone/buildout.coredev and checkout your branch.

**Review by jensens — APPROVED** [review]
Lgtm

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
When I use this branch, creating a Plone Site fails:

```
2021-01-06 19:24:31,239 ERROR   [Zope.SiteErrorLog:252][waitress-3] 1609957471.2394240.5499742942972425 http://localhost:8080/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 364, in publish_module
  Module ZPublisher.WSGIPublisher, line 267, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Products.CMFPlone.browser.admin, line 272, in __call__
  Module Products.CMFPlone.factory, line 136, in addPloneSite
  Module Products.GenericSetup.tool, line 400, in runAllImportStepsFromProfile
   - __traceback_info__: profile-Products.CMFPlone:plone
  Module Products.GenericSetup.tool, line 1478, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1290, in _doRunImportStep
   - __traceback_info__: rolemap
  Module Products.GenericSetup.rolemap, line 100, in importRolemap
KeyError: 'acquire'
```

So you have to add the `acquire` attribute to all permissions in `rolemap.xml`.

**Review by rohnsha0 — COMMENTED** [review]
except one all are good... I guess

**Review by wesleybl — CHANGES_REQUESTED** [review]
We also have it here:

https://github.com/plone/Products.CMFPlone/blob/5852da7247bf9500dce03bc803f4bcb5400d0171/Products/CMFPlone/controlpanel/browser/configure.zcml#L14

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Review by davisagli — COMMENTED** [review]
@jensens @mauritsvanrees There's no upgrade step, so won't this remove access by the Site Administrator role to use these permissions in an existing site? That is not a change I would expect in a patch upgrade.

**Comment by mauritsvanrees** [comment]
I did not think about that!
I tried it, and it indeed goes wrong:

- Start with a Plone 6 site from before this PR.
- Create a user, add to the Site Administrator group.
- Login as this user, check that you can see the Site Setup.  You are allowed because you have the "Plone Site Setup: Overview" permission.
- Update CMFPlone so you have the code of this PR, and restart.
- Try again: you no longer have access to Site Setup.

So we indeed need an upgrade step.
@ewohnlich Are you up for doing that?

Ideally, this could be done, in pseudo code:

```
for permission in rolemap.xml that we changed:
    if permission is already defined at the Plone Site level:
        continue
    Set "acquire" to true.
    Enable Site Administrator role.
```

That should do the trick.  You can get code inspiration from the import step code at `Products/GenericSetup/rolemap.py`.

Easier but possibly overriding changed settings, would be to instead copy the relevant lines from `rolemap.xml` to an upgrade profile in `plone.app.upgrade`.

I am inclined to revert the current PR until an upgrade step is there, but it may be okay to wait a day or two.

**Comment by ewohnlich** [comment]
Sure I will probably have time for this in a bit.

**Comment by ewohnlich** [comment]
@mauritsvanrees should I add this to an existing step in plone.app.upgrade step? And are you thinking it should literally read from the rolemap.xml in Products.CMFPlone, or do I just make a list of permissions from all the ones mentioned here and iterate through that? I'm not sure it's appropriate to read the rolemap.xml in Products.CMFPlone because it's not tied to a specific upgrade step

**Comment by wesleybl** [comment]
@ewohnlich I think you should only be concerned with the permissions defined in this PR. Implementing the pseudo code suggested by @mauritsvanrees  would be nice.

**Comment by ewohnlich** [comment]
Ok. And should this go in plone.app.upgrade?

**Comment by wesleybl** [comment]
> And should this go in plone.app.upgrade?

Yes. upgrades are concentrated there.

**Comment by mauritsvanrees** [comment]
I think I have figured it out, more or less along the lines of what I proposed, but not entirely.  See https://github.com/plone/plone.app.upgrade/pull/313
Please check.

**Pull request merged**
