### PR TITLE
Fix TTW Bundle compilation broken.

### LINKED ISSUE #2969: TTW Bundle compilation broken
Since the integration of plone.staticresources / Plone 5.2 the TTW bundle compilation in ``@@resourceregistry-controlpanel`` is broken.
r.js cannot be found.

### PR DESCRIPTION
**Pull request by thet**
Fixes #2969
Fixes https://github.com/plone/plone.staticresources/issues/58

The PR https://github.com/plone/Products.CMFPlone/pull/2970 got merged for master, which became Plone 6.0 during the Ploneconf sprints IIRC.

### CODE REVIEW

**Comment by davilima6** [comment]
@jenkins-plone-org please run jobs

**Comment by davilima6** [comment]
Code LGTM as it's the same already approved in #2970 Just a curiosity, why was the error handling removed? I'll test it now.

**Comment by davilima6** [comment]
@thet, I still get the error on `buildout.coredev` after changing to `thet-2969-5.2.x` branch of `src/Product.CMFPlone`, starting the instance and creating a fresh site. Am I missing some step?

**Comment by davilima6** [comment]
Actually the error now is a bit different. Before it was:

```
GET http://localhost:8080/Plone2/++plone++static/components/r.js/dist/r.js net::ERR_ABORTED 404 (Not Found)
Uncaught TypeError: Cannot read property 'optimize' of undefined
    at Object.onLoad (resourceregistry-compiled.js:33643)
    at window.IFrame.load (resourceregistry-compiled.js:33406)
```

Now the first error is different:

```
Uncaught SyntaxError: Invalid or unexpected token
resourceregistry-compiled.js:33643 Uncaught TypeError: Cannot read property 'optimize' of undefined
    at Object.onLoad (resourceregistry-compiled.js:33643)
    at window.IFrame.load (resourceregistry-compiled.js:33406)
```

Can you reproduce?

**Comment by davilima6** [comment]
It seems an unexpected shebang got prepended to the `r.js` file:

http://localhost:8080/Plone/++plone++static/components/requirejs/bin/r.js

```
#!/usr/bin/env node
/**
 * @license r.js 2.3.6 Copyright jQuery Foundation and other contributors.
 * Released under MIT license, http://github.com/requirejs/r.js/LICENSE
 */

/*
 * This is a bootstrap script to allow running RequireJS in the command line
 * in either a Java/Rhino or Node environment. It is modified by the top-level
 * dist.js file to inject other files to completely enable this file. It is
 * the shell of the r.js file.
 */

/*jslint evil: true, nomen: true, sloppy: true */
/*global readFile: true, process: false, Packages: false, print: false,
console: false, java: false, module: false, requirejsVars, navigator,
document, importScripts, self, location, Components, FileUtils */

var requirejs, require, define, xpcUtil;
(function (console, args, readFileFunc) {
    ...
```

**Comment by mtrebron** [comment]
Looks good from here!

**Comment by davilima6** [comment]
Update: Firefox parser seems to be more permissive and despite some malformed XML errors in console, TTW build works for me.

**Comment by davilima6** [comment]
[Failures](https://jenkins.plone.org/job/pull-request-5.2/804/console) seem unrelated:

```
Error in test test_all_supported_languages (plone.app.multilingual.tests.test_setup.TestSetupMultilingualSite)
Traceback (most recent call last):
  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.multilingual-5.5.0-py2.7.egg/plone/app/multilingual/tests/test_setup.py", line 49, in test_all_supported_languages
    setup_tool.setupSite(self.portal)
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.multilingual-5.5.0-py2.7.egg/plone/app/multilingual/browser/setup.py", line 79, in setupSite
    doneSomething += self.setUpLanguage(language, name)
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.multilingual-5.5.0-py2.7.egg/plone/app/multilingual/browser/setup.py", line 152, in setUpLanguage
    self.context[folderId], assets_folder_id)
  File "/home/jenkins/workspace/pull-request-5.2@4/src/Products.CMFPlone/Products/CMFPlone/utils.py", line 351, in _createObjectByType
    id = str(id)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)



Error in test test_type_of_language_folders (plone.app.multilingual.tests.test_setup.TestSetupMultilingualSite)
Traceback (most recent call last):
  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.multilingual-5.5.0-py2.7.egg/plone/app/multilingual/tests/test_setup.py", line 69, in test_type_of_language_folders
    setup_tool.setupSite(self.portal)
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.multilingual-5.5.0-py2.7.egg/plone/app/multilingual/browser/setup.py", line 79, in setupSite
    doneSomething += self.setUpLanguage(language, name)
  File "/home/jenkins/.buildout/eggs/cp27m/plone.app.multilingual-5.5.0-py2.7.egg/plone/app/multilingual/browser/setup.py", line 152, in setUpLanguage
    self.context[folderId], assets_folder_id)
  File "/home/jenkins/workspace/pull-request-5.2@4/src/Products.CMFPlone/Products/CMFPlone/utils.py", line 351, in _createObjectByType
    id = str(id)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
```

**Comment by thet** [comment]
@davilima6 I'll restore the r.js and less.js files in the versions we were using until plone.staticresources - including the patches applied like mentioned here: https://github.com/plone/plone.staticresources#warning
I'll provide these resources out from the npm upgrade process in a seperate directory which also includes an upgrade step. TTW compilation - IIRC - will only be available until Plone 6 or so. requirejs should go away in favor of standard ES6 imports.

I already started but will finish later this weekend.

**Pull request merged**
