### PR TITLE
change IImagingSchema default allowed sizes to unicode

### PR DESCRIPTION
**Pull request by kuetrzi**
Bug fix for WrongContainedType: ([WrongType('large 768:768', <type 'unicode'>, '')...
which is raised if adding values to registry via generic setup profiles (registry.xml). Default values set in Schema are not unicode.

### CODE REVIEW

**Comment by gforcada** [comment]
Tests running here: http://jenkins.plone.org/job/pull-request-5.0/524/

**Comment by gforcada** [comment]
@kuetrzi on the meantime, did you sign the [contribution agreement](https://plone.org/foundation/contributors-agreement)? To legally be able to contribute to plone one needs to sign it.

**Comment by kuetrzi** [comment]
@gforcada thanks for running tests. Contributor agreement is all sorted (many years ago).

**Comment by gforcada** [comment]
@kuetrzi I asked for the contributor agreement because on your github profile you are not part of the plone organization... sorry to bother.

On a more related topic, there are test failures, would you care looking at them?

**Comment by mauritsvanrees** [comment]
@kuetrzi When I want to know if a person has signed the contributor agreement, I often look at their github account and check if the Plone organisation is listed there. In your case it is not there, as you have chosen to keep this information private. That might be the default.
When I look at https://github.com/orgs/plone/people?utf8=✓&query=kuetrzi I see you are in the list, so all is well. If you want to, you can choose to make your account public there.  This is up to you. Feel free to keep it as it is.
I am just mentioning this so you know why @gforcada thought you may not have signed the contributor agreement. :-)

BTW, you should feel free to create branches in the original Plone repositories too. This allows others to continue on your work in case this is needed. But do whatever works for you.

I see there is a test failure, but this has nothing to do with your pull request and I have just merged another pull request that fixes this particular failure.  So all looks good to me. I will merge. Thanks!

**Comment by mauritsvanrees** [comment]
Oh, I thought I saw you did the pull request on a fork, but this is not the case. Sorry. Forget my remark about that.

**Comment by kuetrzi** [comment]
@mauritsvanrees thanks for sorting things out, I have changed my profile.
@gforcada it wasn't a bother and thanks for your help, sorry that my profile wasn't more helpful. But its sorted now.

**Comment by mauritsvanrees** [comment]
@kuetrzi Thanks. BTW, from glancing at the members list, it seems like maybe half of the people have their membership private.

**Pull request merged**
