### PR TITLE
fix role map for `Show Toolbar Permission`

### PR DESCRIPTION
**Pull request by fgrcon**
see end of discussion of https://github.com/plone/Products.CMFPlone/issues/1570

### CODE REVIEW

**Comment by hvelarde** [comment]
@fgrcon be careful with this: the toolbar must be fixed as a whole and not just to solve your specific use case.

as mentioned before, I agree with @jensens: all authenticated users must see at least a toolbar with the personal bar or we'll be creating new basic usability problems like user doesn't know she is logged-in and user doesn't know how to log out.

if you want to hide the toolbar on your projects, do that as part of your policy.

**Comment by jensens** [comment]
yes, please add Authenticated to the defaults - if you then remove it in your policy thats fine.

**Comment by fgrcon** [comment]
absolutely sure about that. ;-)

**Comment by fgrcon** [comment]
Bye

**Comment by fgrcon** [comment]
Bye

**Comment by fgrcon** [comment]
after a while (but still  a little bit annoyed ...)
@hvelarde: I really would appreciate that you start reading stuff more carefully before commenting. This is a regression in ux/ui. Untill Plone 4.x  an authenticated user only saw a toolbar (edit bar) when he had the appropriate locale roles. 

@jensens:  adding authenticated renders all of  @agitator s changes useless. But if you prefer to force plone users to create policies  for something which really should be default behavior - well ok for me  ..

**Comment by agitator** [comment]
@fgrcon you are right about the "regression"

uiwise there is the problem that the personal actions would switch between top-right and bottom left depending on the users permission, which would be inconsistent.

in my usecase, an intranet, i'm adding additional edit-tools within the content area and never show the toolbar for that role, so that the user doesn't have that inconsistency.

**Comment by hvelarde** [comment]
@fgrcon of course we have a regression and many other problems related to the toolbar: previously we had different elements: an edit bar and a personal bar, among them; today we have only one big toolbar with huge UI/UX problems and I've being pointing to them even before the release of Plone 5: #957.

you are messing around the `Show Toolbar` permissions, not just the edit part of it; you were just about to create more problems, because you're not thinking the whole picture but only in solving your problem.

so start by being careful yourself and be also open to criticism, @jensens had already rose the concern before me and you just ignored both of us.

**Comment by jensens** [comment]
The problem of a more consistent editing UI is bigger than a bunch of small fixes introducing new problems. I hope Pastanaga will help in future. We may also improve the current toolbar, but this need to be done carefully with discussions, probably best at a sprint or conference with a wide variety of Plonistas attending.

**Pull request closed without merging**
