### PR TITLE
Deprecate the portal_properties tool

### PR DESCRIPTION
**Pull request by ale-rt**
The tool gets most of the methods from OFS.PropertyManager.

The most relevant are using internally the hasProperty method.

Deprecating this should be enough to finally start removing this obsolete tool and a bunch of code that depends on that.

Refs. #125

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
Is there a porting guide from properties_tool to the registry? It would be great to add a link on those deprecations, so one can easily follow the link and get it ported ✨

**Comment by ale-rt** [comment]
I do not think so.
What about linking #125, the issue where the discussion about removing the tool happened?

**Comment by jensens** [comment]
Please always tell in depreciation message when it will be removed, like in Plone 7 (or 6.1)...

**Comment by ale-rt** [comment]
The discussion about removing portal properties dates back in 2013 and [the plan was to remove it in 5.1](https://github.com/plone/Products.CMFPlone/issues/125#issuecomment-141768802).

I would target 6.1: there is really a lot of junk code that we can drop, especially in the tests.

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Pull request merged**
