### PR TITLE
Pyupgrade

### PR DESCRIPTION
**Pull request by jensens**
Applied ``find . -name "*.py" |grep -v skins|xargs pyupgrade --py36-plus --py3-only``.
Lets see what Jenkins says.

### CODE REVIEW

**Comment by pbauer** [comment]
`--py3-only` is obsolete here. `--py36-plus` is enough and will give us f-strings :)

**Comment by mauritsvanrees** [comment]
I would also say use `--py36-plus`. Let's have all changes in one commit.

**Comment by jensens** [comment]
Doesn't `--py36-plus` implies `--py3-only` already?

**Comment by mauritsvanrees** [comment]
`--py36-plus` implies `--py3-only`, but not the other way around.

**Comment by jensens** [comment]
to merge or not to merge, that's here the question....

**Comment by pbauer** [comment]
I'm generally +1 but I want it with f-strings. When I run the command `find . -name "*.py" |grep -v skins|xargs pyupgrade --py36-plus` I get at least some some f-strings, e.g. in https://github.com/plone/Products.CMFPlone/pull/3185/files#diff-1582a68636fd8187555ca419b38fce6cL306 your result is `'{}/{}'.format(category, id)` whereas mine is `f'{category}/{id}'`, which I prefer.
Can you please do again the same without `--py3-only`?

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
