### PR TITLE
Plip 3395 plone base

### PR DESCRIPTION
**Pull request by jensens**
see #3395

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Slightly easier: `bin/test -u` fails with the same traceback, during test layer setup. End result is:

      Ran 2040 tests with 6 failures, 79 errors, 2 skipped in 16.880 seconds.

**Comment by mauritsvanrees** [comment]
I confirm the tests pass locally (at least the ones that failed earlier for me). I have restarted the PLIP jobs.

**Comment by jensens** [comment]
FTR: link to plip-jobs/3.9 https://jenkins.plone.org/view/PLIPs/job/plip-3395-plone.base-part-1-3.9/

**Comment by jensens** [comment]
And PLIP jobs are green!

**Comment by mauritsvanrees** [comment]
For me it would be good to merge.

@plone/framework-team  have a look at the implementation please.

**Comment by ale-rt** [comment]
I had a look to the `plone.base` package but I am struggling to find the time for an in depth review.

It seems well crafted but I have some doubts.

The [`defaultpage`](https://github.com/plone/plone.base/blob/6e26a377f7153ea6631a6ad58b7a9008fd3d6e53/src/plone/base/defaultpage.py) module pulls in quite a lot of dependencies that otherwise could be dropped and the content is not really something that survived well the time.
Does it really make sense to move it to a new package?

I also noted this [`deprecation`](https://github.com/plone/plone.base/blob/6e26a377f7153ea6631a6ad58b7a9008fd3d6e53/src/plone/base/batch.py#L28) in the `batch` module with a long explanation.

That also feels weird, either we revert the deprecation or remove the code.

That said I already asked if somebody of the @plone/framework-team has some time to review this one.
If in the next week:
1. the tests are green again
2. you think the things I mentioned above are not blockers or something which is worth investing time fixing
3. nobody else from the @plone/framework-team jumps in to (at least) propose review this one

I would just say that you should feel free to push the merge button.

**Comment by ale-rt** [comment]
One other thing... I think we lost some tests.
See https://github.com/plone/plone.base/blob/6e26a377f7153ea6631a6ad58b7a9008fd3d6e53/src/plone/base/utils.py#L69

It mentions `safe_unicode` which is not something we have in that package.
Probably it is way easier to move those doctests in some unitest.

**Comment by jensens** [comment]
> The [`defaultpage`](https://github.com/plone/plone.base/blob/6e26a377f7153ea6631a6ad58b7a9008fd3d6e53/src/plone/base/defaultpage.py) module pulls in quite a lot of dependencies that otherwise could be dropped and the content is not really something that survived well the time.

Indeed. But this might get refactored later. OTOH defaultpage is used by a bunch of plone.app.* packages, so it has to be moved to somewhere. Probably to `Products.CMFDynamicViewFTI`? But we can move it further later, right? I am happy having it that far down for now.

> I also noted this [deprecation](https://github.com/plone/plone.base/blob/6e26a377f7153ea6631a6ad58b7a9008fd3d6e53/src/plone/base/batch.py#L28) in the batch module with a long explanation. 
> 
> That also feels weird, either we revert the deprecation or remove the code.

This is true, but IMO out of scope here. We can tackle this on a different PR later.

**Comment by jensens** [comment]
> One other thing... I think we lost some tests. See https://github.com/plone/plone.base/blob/6e26a377f7153ea6631a6ad58b7a9008fd3d6e53/src/plone/base/utils.py#L69
> 
> It mentions `safe_unicode` which is not something we have in that package. Probably it is way easier to move those doctests in some unitest.

It  seems in a former copy paste session the docstring was copied, but never reviewed. The test does not make any sense for `safe_text` and been probably never run. This would need indeed some love, but also IMO out of scope here.

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Oops, starting Jenkins via a comment here is not very useful. I stopped the jobs and started the proper PLIP jobs instead.

**Comment by jensens** [comment]
All green. IMO ready for merge?

**Pull request merged**
