### PR TITLE
Fix #2917: Now PasswordResetView::getErrors is called

### LINKED ISSUE #2917: PasswordResetView::getErrors function never called.
### What I did:
I am trying to reset the password, using a normal Plone user and I made a PDB inside https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/login/password_reset.py#L159

URL: {site url}/passwordreset/e3127df738bc41e1976cc36cc9832132?userid=local_manager

### What I expect to happen:
I expected a call `RegistrationTool.testPasswordValidity(password, password2)
` as I have some business logic inside testPasswordValidity but I saw code never coming here

### What actually happened:
As I see inside ''getErrors''  method, there is a call to registration tool testPasswordValidity method but the ''getErrors'' never called.
### What version of Plone/ Addons I am using:
Plone 5.2.5rc

### PR DESCRIPTION
**Pull request by nazrulworld**
Issue #2917

### CODE REVIEW

**Comment by nazrulworld** [comment]
@jenkins-plone-org please run jobs

**Comment by nazrulworld** [comment]
> Thanks @nazrulworld, LGTM
> Also thanks to @benkummer.
> 
> Can you please add a `news/2917.bugfix` file with a changelog line?
> See other examples here: https://github.com/plone/Products.CMFPlone/tree/master/news

I have added, thanks a lot.

**Comment by nazrulworld** [comment]
@ale-rt will you merge this PR or should I?

**Comment by ale-rt** [comment]
Once it is approved and the test pass you have the go for pressing the merge button :)

**Pull request merged**
