### PR TITLE
recompiled resources to fix broken logged-in bundle

### LINKED ISSUE #2395: Folder contents tree navigation broken in Plone 5.1.2
### What I did:

1. Create a Plone 5.1.2-pending Site.
2. Create a nested structure with some folders and pages
3. Navigation within `folder_contents` to a deeper lever.
4. Click `Edit` Button in toolbar.

### What I expect to happen:

Edit navigated page

### What actually happened:

URL points to the folder the navigation started.

### What version of Plone/ Addons I am using:

Plone 5.1.2-pending (minimal)
No Addons.

This works with Plone 5.1.1.

### PR DESCRIPTION
**Pull request by MrTango**
recomplied resources to fix #2395

### CODE REVIEW

**Comment by tomgross** [comment]
I think this also needs an updated timestamp in the registry so the resources are picked up.

**Comment by MrTango** [comment]
Somehow some robot test are failing now, i currently don't have time to dive into it, maybe some one else can help.

**Comment by petschki** [comment]
I've recreated the resources with this pull request https://github.com/plone/mockup/pull/854 and tests are now green. @thet willing to approve this pull request?

**Comment by MrTango** [comment]
maybe we can fix this one too, before we deliver the update: #1906

**Comment by petschki** [comment]
@MrTango #1906 needs a fixing pull request in plonetheme.barceloneta first ... I'll try my best this week

**Comment by petschki** [comment]
see https://github.com/plone/plonetheme.barceloneta/pull/156 ... but maybe we should close this instead of waiting for another pull request...

**Comment by frapell** [comment]
@petschki @MrTango The latest changes from mockup requires to include the datatables lib as well into the components directory.

If you can wait, I think I can commit the new compiled resources and all needed components, on all of the branches for CMFPlone later tonight

**Comment by frapell** [comment]
New bundles are in https://github.com/plone/Products.CMFPlone/pull/2471

**Comment by thet** [comment]
Closing in favor of https://github.com/plone/Products.CMFPlone/pull/2471

**Pull request closed without merging**
