### PR TITLE
since short name is controlled by behaviors now

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
tests: http://jenkins.plone.org/job/pull-request-5.0/299/

**Comment by vangheem** [comment]
test again: http://jenkins.plone.org/job/pull-request-5.0/300/

**Comment by vangheem** [comment]
@esteele I'm not sure how archetypes in affected. I grepped the visibleIdsEnabled method and it isn't used anywhere.

**Comment by vangheem** [comment]
and one more time: http://jenkins.plone.org/job/pull-request-5.0/301/

**Comment by pbauer** [comment]
I tested that with Archetypes in Plone 5 and there are no issues. The field to edit a id does not show up anymore but you can always rename the id of an item using rename or bulk-rename.

**Comment by hvelarde** [comment]
@vangheem you're missing a changelog entry; also, this kind of things should be clearly documented in some place.

@polyester @svx FYI

**Pull request merged**
