### PR TITLE
Do not create title tag for svg icons when tag_alt is not given

### PR DESCRIPTION
**Pull request by agitator**

### CODE REVIEW

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Review by petschki — APPROVED** [review]

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by rohnsha0** [comment]
@jenkins-plone-org please run jobs

**Review by rohnsha0 — APPROVED** [review]

**Pull request merged**
