### PR TITLE
Prevent loading of css at nav_root_url

### PR DESCRIPTION
**Pull request by krissik**
If 'tinymce-content-css' option is missing in themes manifest.cfg its default value is `''` (see https://github.com/plone/plone.app.theming/blob/98e8285f9c22700414671a1cdb191e4f903ef3f5/src/plone/app/theming/utils.py#L328). If we check only for `None` here an unnecessary request to nav root is triggered.

I found that while improving performance. It looked like that:
unnecessary_css

### CODE REVIEW

**Comment by krissik** [comment]
@jenkins-plone-org please run jobs

**Comment by krissik** [comment]
@jenkins-plone-org please run jobs

**Comment by krissik** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by djowett-ftw** [comment]
I see this in Plone 5.1.6.  Could this fix be merged to 5.1.x also?

**Comment by jensens** [comment]
@djowett-ftw would be great if you can take over here? I do not understand the problem well and if tests are green and you think all is fine, please merge this one and prepare a backport.

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
Backport for 5.2 in #3101

**Pull request merged**
