### PR TITLE
Base tag differs from actual URL

### PR DESCRIPTION
**Pull request by rodfersou**
closes https://github.com/plone/plone.app.layout/issues/86

### CODE REVIEW

**Comment by rodfersou** [comment]
@plone/framework-team can someone take a look at these PR please?

**Comment by jensens** [comment]
@rodfersou needs rebase, thanks!

**Comment by rodfersou** [comment]
@jensens done

**Comment by rodfersou** [comment]
@jensens don't forget that this pull request is related with this pull request too: https://github.com/plone/plone.app.layout/pull/87

**Comment by rodfersou** [comment]
New jenkins job: http://jenkins.plone.org/job/pull-request-4.3/369/console

**Comment by rodfersou** [comment]
@jensens @hvelarde green

**Comment by jensens** [comment]
ok from my side. I'd like to have someone with more insight on base tag to have a quick look. 

@thet, iirc you fiddled in past with base tags?

This needs merge together with plone/plone.app.layout/pull/87

**Comment by jensens** [comment]
do we need this in 5.1 too or was this fixed there alrready?

**Comment by hvelarde** [comment]
this is for Plone 4 only; on Plone 5 the `<base>` tag was removed long ago.

**Comment by rodfersou** [comment]
:clap:

**Pull request merged**
