### PR TITLE
Include pat-moment for public javascript

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
tests: http://jenkins.plone.org/job/pull-request-5.0/894/

**Comment by vangheem** [comment]
If this is merged, https://github.com/plone/plone.app.upgrade/pull/67 should be merged as well.

**Comment by vangheem** [comment]
grrr, failed because of missing imports required from https://github.com/plone/plone.app.upgrade/pull/67

Can we merge https://github.com/plone/plone.app.upgrade/pull/67 first?

**Comment by jensens** [comment]
you can put two PRs in one jenkins build. I did so with http://jenkins.plone.org/job/pull-request-5.0/896
lets wait and see

**Pull request merged**
