### PR TITLE
Update TinyMCE to 4.7.13 in master

### PR DESCRIPTION
**Pull request by erral**

### CODE REVIEW

**Comment by sunew** [comment]
@erral the changelog has been garbled again - a lot of old stuff has sneaked in.

**Comment by sunew** [comment]
@erral (I just merged a cleanup not long ago - see https://github.com/plone/Products.CMFPlone/commit/d07d596bb78df07271ddfdb18636a8181afbef88 )

**Comment by sunew** [comment]
@erral we also need an update of the bundle dates in pa.upgrade, but I'm merging in https://github.com/plone/mockup/pull/863 so I guess it will be covered by that update. (I'll do a PR for pa.upgrade as well)

**Comment by erral** [comment]
I see, I rebased on top of master when saw your changes, but it looks like CHANGES's ones where not applied correctly. I have just fixed them.

**Pull request merged**
