### PR TITLE
rebuild resources after fixing plone/plonetheme.barceloneta/issues/62

### PR DESCRIPTION
**Pull request by fgrcon**

### CODE REVIEW

**Comment by fgrcon** [comment]
http://jenkins.plone.org/job/pull-request-5.0/

**Comment by fgrcon** [comment]
http://jenkins.plone.org/job/pull-request-5.0/557

**Comment by vangheem** [comment]
One failure here. Can you take a look?

**Comment by fgrcon** [comment]
dont know, what really happens here (maybe some other changes in the meantime helped), failing test succeeds now, when I run it locally.:
````
root@debian:/usr/local/p5dev/buildout.coredev# bin/robot src/Products.CMFPlone/Products/CMFPlone/tests/robot/test_linkintegrity.robot
==============================================================================
Test Linkintegrity                                                            
==============================================================================
Scenario: When page is linked show warning                            | PASS |    <--------- this one failed before
------------------------------------------------------------------------------
Scenario: After you fix linked page no longer show warning            | PASS |
------------------------------------------------------------------------------
Scenario: Show warning when deleting linked item from folder_contents | PASS |
------------------------------------------------------------------------------
Test Linkintegrity                                                    | PASS |
3 critical tests, 3 passed, 0 failed
3 tests total, 3 passed, 0 failed
````

New try: http://jenkins.plone.org/job/pull-request-5.0/564

**Pull request merged**
