### PR TITLE
upgrade tinymce

### PR DESCRIPTION
**Pull request by vangheem**
Hi all, we need to upgrade TinyMCE and it seems like the update to 4.2.5 changes the look and feel a bit for TinyMCE.

screen shot 2015-09-10 at 11 58 29 pm

What does everyone think about this?

### CODE REVIEW

**Comment by frapell** [comment]
I am +1 with upgrading, the jump from tinymce 3.x was bigger than this, so I don't see why we shouldn't do it this time?

**Comment by jensens** [comment]
overall +1 here too - but question is if we want to do this in Plone 5 RC phase? What does our release manager @esteele think?

**Comment by esteele** [comment]
Please go ahead and update this.

**Comment by vangheem** [comment]
tests running: http://jenkins.plone.org/job/pull-request-5.0/293/

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/292/

**Pull request merged**
