### PR TITLE
Include TinyMCE 4.5.6

### PR DESCRIPTION
**Pull request by frapell**
While I figure out what's going on with 4.6.1 from https://github.com/plone/mockup/pull/764 bring in a newer TinyMCE from https://github.com/plone/mockup/pull/766

### CODE REVIEW

**Comment by frapell** [comment]
Proper pull request located at https://github.com/plone/mockup/pull/767

**Comment by thet** [comment]
LGTM

**Comment by thet** [comment]
@frapell two things were missing. I just added them myself, as I'm currently also working on mockup/cmfplone.

- plone.app.upgrade step: https://github.com/plone/plone.app.upgrade/pull/121
- CMFPlone registry.xml updates: https://github.com/plone/Products.CMFPlone/pull/2055/commits/5e678e79acf04167f25dddde91d2f1c3b2f6f2d3

Both are tested along with other changes here:
https://github.com/plone/Products.CMFPlone/pull/2055
http://jenkins.plone.org/job/pull-request-5.1/92/

**Comment by frapell** [comment]
Ahh, yes! thanks for those :)

**Pull request merged**
