### PR TITLE
Add image srcset's configuration to TinyMCE pattern settings

### PR DESCRIPTION
**Pull request by MrTango**
All PR's:

- https://github.com/plone/Products.CMFPlone/pull/3477
- https://github.com/plone/plone.base/pull/5
- https://github.com/plone/mockup/pull/1156
- https://github.com/plone/plone.outputfilters/pull/49

needs an upgrade step in plone.app.upgrades to load the config

### CODE REVIEW

**Comment by tisto** [comment]
@MrTango did you take into consideration that we might want to add srcet configuration in the control panel for Volto at some point as well?

**Comment by MrTango** [comment]
Since it is JSON, that should be possible. And it is already accessible in the imaging control panel.
If you have opinions about the settings it self, i'm happy to here them.
Right now i have implemented the setting and made TinyMCE use it. 
The actual srcset's in Classic UI, will be generated in output filters similar to how captions are rendered now.
It would be good to have the srcset config compatible with Volto.

**Comment by MrTango** [comment]
@tisto i updated the PR with a JSON Schema defintion of the srcset config, the interface lives now in plone.base: https://github.com/plone/plone.base/pull/5
let me know what you thing.

**Comment by MrTango** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@MrTango I have reopened this PR, I think it was closed by accident at some point.

I have restored the previous `imageScales` in the patterns settings. I think we temporarily still need them. See my reasoning in commit 40be9133dd26ea159e52320c966616710b61394f.
Also merged master in here a few times.

Before this change I started a PR job. Robot tests are fine, but in the console you can see [10 failures, 4 errors](https://jenkins.plone.org/job/plip-plip-image-srcsets-3.9/3/console). I am having a look at some `plone.restapi` errors.

**Review by pbauer — APPROVED** [review]

**Review by jensens — APPROVED** [review]

**Review by agitator — APPROVED** [review]

**Pull request merged**
