### PR TITLE
Restore ability to include head when loading via ajax

### PR DESCRIPTION
**Pull request by displacedaussie**
When loading a page using `ajax_load`, `ajax_main_template.pt` is used instead of `main_template.pt`. The ajax template loads a simplified version of the page.

Previously it was possible to set `ajax_load_with_header`/`ajax_include_head` to include the CSS/JS for the page, but this ability is now missing.

This change restores the ability to load everything in `<head>` (plone.htmlhead, head_slot, javascript_slot, css_slot etc.) if desired.

### CODE REVIEW

**Comment by djay** [comment]
@jensens how do we get this reviewed?

**Comment by jensens** [comment]
@djay LGTM, nice regression catch. If you want to simplify a merge it is best if you first start the tests on your own (I'll post the short instruction below). I'll do so for now.

---------------------------

You can always start a Jenkins test-job on your own to test that your pull request (PR) does not break anything. 

Below click on the link to Jenkins
screenshot from 2016-07-25 11 20 06

**log in** with your Github user - if not already done before.

Paste the full **pull request URL** into the text field (if multiple pull requests need to be combined in one run, then one PR URL per line)

Click on **Build**

Jenkins reports back to the pull request(s) on Github in the status box at the bottom.

In Plone we value a lot our testing suite, so we usually never merge pull requests if they have not been tested by Jenkins first.

**Comment by djay** [comment]
This is still broken in 5.0.7. Seems it only got merged in the 5.1 branch. Is it possible to get this into the 5.0.x branch? @jensens @instification

**Comment by mauritsvanrees** [comment]
A pull request to get this into Plone 5.0.x would be good.

**Comment by instification** [comment]
@mauritsvanrees I have created a PR https://github.com/plone/Products.CMFPlone/pull/2070

**Comment by mauritsvanrees** [comment]
I have merged your PR to 5.0. Thanks.

**Comment by mauritsvanrees** [comment]
BTW, it is too late to be added to Plone 5.0.8, which is already in pending mode, so it should end up in 5.0.9.

**Comment by mauritsvanrees** [comment]
Inf act, 5.0.8 is out already, but not yet officially announced, pending release of the installers.

**Comment by instification** [comment]
Thanks Maurits :smile:

**Pull request merged**
