### PR TITLE
On Zope root, create Volto site by default.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
When the `plone.volto` package is not available, the buttons are the same as before,
and will create a Classic Plone site.

When `plone.volto` is there, you get an extra button for Classic:

Screenshot 2021-10-27 at 10 12 57

- 'Create a new Plone site' will create a Volto site.
- 'Create Classic Plone site' will create a Classic site.
- Advanced still gives you all options. The extra Volto profiles are selected when available.

We could pick different colors.

When installing Volto, we install the caching and Barcelonata profiles just like a Classic site,
although we could choose to not install Barceloneta.
As extra, we install `plone.volto:default` and `plone.volto:default-homepage`.
(Technically, `default-homepage` would already pull in `default`, but let's do this explicitly.)

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Review by sneridagh — APPROVED** [review]
+1 what @tisto said.

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by ericof** [comment]
I'm a bit late to the party, but I do think we should merge this but then refactor the logic out of the browser view and into the `factory.py` module.

**Review by ericof — APPROVED** [review]

**Pull request merged**
