### PR TITLE
Catch more errors in generating scripts listing when bundle resources…

### PR DESCRIPTION
**Pull request by fredvd**
… cannot be found.

### CODE REVIEW

**Comment by fredvd** [comment]
Test is not complete, it tests now if the combine bundle is still working, but the missing KeyError in Bundle class its realpath method is not triggered with the current test.

The traversing to a broken path/resource triggers either a KeyError, AttributeError or a NotFound, I think it depends on an already missing path or ++resource++ (I'm using notfound in the test) or a missing file 'in' the ++resource++does.exist/missing-file.js . 

Are there any other existing ++resource++ locations I can us in a test?

**Comment by fredvd** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by fredvd** [comment]
> LGTM, although I am not sure why in one case you except AttributeError and in another KeyError. Maybe do both. But maybe you have a reason. And this already seems a helpful improvement.

I only used these to be on the conservative side with swallowing Exceptions. I ran into this problem locally and pdb'ed through the code to see where which exception was raised and only added the Exceptions which were triggered in this case. 

My first try was the compile code, and when I fixed that the bundle process threw this.   This PR at solves part of the frustration of making one typo in resource registry config and breaking the whole Plone site, but I'm not an expert here.

**Comment by mauritsvanrees** [comment]
Well, seems an improvement to me. I will merge.

**Pull request merged**
