### PR TITLE
remove deprecated icons ...

### PR DESCRIPTION
**Pull request by fgrcon**
https://github.com/plone/Products.CMFPlone/issues/1151

### CODE REVIEW

**Comment by jensens** [comment]
wait for the other to be merged

**Comment by vangheem** [comment]
http://jenkins.plone.org/job/pull-request-5.0/471

**Comment by gforcada** [comment]
Everyone deserves a second chance: http://jenkins.plone.org/job/pull-request-5.0/478/

**Comment by fgrcon** [comment]
@gforcada @vangheem 
 I think, the test in plone/app/portlets/tests/test_navigation_portlet.py testImgConditionalOnTypeIcon
 is outdated now (or i don't understand it yet). 

In Plone 5 contenttype-icons are rendered with css::before ... . That means for each new dexterity contenttype we need  to add a related css rule. The icon_property in the fti seems useless there (btw  all are null for the default types in p.a.contenttypes).

**Can we just delete this ( and similar) test(s) ?**

btw: the prs in https://github.com/plone/Products.CMFPlone/issues/1151 should be tested all together
(i am just working on mockup/patterns/relateditems, found some flaws...)

**Comment by gforcada** [comment]
@fgrcon then create a pull request on p.a.portlets removing the test, or asking for advice on how to proceed there (maybe a branch needs to be created to work only on Plone 4 and keep master Plone 5 only).

**Comment by jensens** [comment]
``plone.app.portlets`` is on 2.5.x branch in Plone 4 and on master on Plone 5, so you can safely adjust the test in master

**Comment by fgrcon** [comment]
I updated   plone/plone.app.portlets#59 (deprecated test case) 
also new plone/plone.app.contentlisting#10 (2 deprecated testcases). Run all tests locally - no Failures.
Both prs might be necessary for testing CMFPlone. (See all related prs in https://github.com/plone/Products.CMFPlone/issues/1151).

I failed to start a jenkins job - any hints?

**Comment by gforcada** [comment]
@fgrcon where did you get stuck on the process to run a jenkins job?

**Comment by thet** [comment]
Maybe like me, not finding the URL via the jenkins.plone.org navigation menu... I always use this as bookmark: https://github.com/plone/jenkins.plone.org/issues/119#issuecomment-115072293

You can start a pull-request jenkins job here:
http://jenkins.plone.org/job/pull-request-5.0/build
- Add the github URL to your pull request in the textfield (just one line at the moment... multiple pull-requests may be supported later)
- Press the "Build" button below the textfield (not the "Build all").

**Comment by fgrcon** [comment]
rebased:
@thet @gforcada  Thanks for the hint! Seems to work now.

**Comment by fgrcon** [comment]
tests fail again of course ,,,

As i said befor this require at least  plone/plone.app.portlets#59 (deprecated test case)
maybe also new plone/plone.app.contentlisting#10 (depends on the tests  defined)

**Comment by fgrcon** [comment]
temporary closed see: plone/Products.CMFPlone#1226

**Pull request closed without merging**
