### PR TITLE
fix HTMLFilter default value type unicode

### PR DESCRIPTION
**Pull request by petschki**
Fix for #3103

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@mauritsvanrees this is a small fix for HTMLFilter default values. since there's a bug in #3104 which broke the Plone5.2py2 build I'd love to get this merged, but somehow Jenkins PR5.1 needs to get passed here ... do you know why? or can u force-merge this w/o jenkins check?

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
I do not know either what is happening here :/ I tried rebasing and squashing commits here #3111 and here #3110 but the list of jobs was never the right one.
CC @gforcada

**Comment by petschki** [comment]
@ale-rt thanks for your effort ... very strange...

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I guess the 5.1 PR job was started accidentally, and now it stays in the checks.
LGTM. I will merge.

**Pull request merged**
