### PR TITLE
Fix scripts.pt Parsing Errors & Self-Closing Tags

### PR DESCRIPTION
**Pull request by Netroxen**
This resolves the issue found in: https://github.com/plone/Products.CMFPlone/issues/2870

### Note

Normally self closing tags are fine to use, but for whatever reason, the template is parsed incorrectly when NOT using Diazo. To fix this I have reverted the template to using full tags.

### CODE REVIEW

**Comment by Netroxen** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
We no longer use the `CHANGES.rst` directly, but use towncrier instead. Please add a ``news/2871.bugfix`` file with your changelog and remove the line from `CHANGES.rst`

@mauritsvanrees we used to have a comment stating this at the top of `CHANGES.rst`, but it is gone. May we have it back?

**Comment by Netroxen** [comment]
> We no longer use the `CHANGES.rst` directly, but use towncrier instead. Please add a `news/2871.bugfix` file with your changelog and remove the line from `CHANGES.rst`
> 
> @mauritsvanrees we used to have a comment stating this at the top of `CHANGES.rst`, but it is gone. May we have it back?

Alrighty, I added the news file to the merge-request. Sorry for the inconvenience!

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by Netroxen** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
