### PR TITLE
new version of mockup from thet-pickadate-clearandset-2.1.x branch

### PR DESCRIPTION
**Pull request by thet**
https://github.com/plone/mockup/pull/731

/cc @tomgross

### CODE REVIEW

**Comment by thet** [comment]
http://jenkins.plone.org/job/pull-request-5.0/1780/

**Comment by thet** [comment]
http://jenkins.plone.org/job/pull-request-5.0/1788/

**Comment by tomgross** [comment]
@thet Thanks for the code! This has probably nothing to do with your code but compiling the code in the browser gives me the following traceback in the Plone 5.0.x branch
```
2017-02-07 08:25:42 ERROR Zope.SiteErrorLog 1486452342.990.0248622759892 https://webcms.dev.fhnw.ch/less-variables.js
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.resources.browser.mixins, line 71, in __call__
NameError: global name 'SafeFormatter' is not defined
```

**Comment by thet** [comment]
@tomgross see comments in referenced PRs above.

**Comment by mauritsvanrees** [comment]
Ah, well spotted.
I have made pull requests #1944 and #1945 to fix this.

**Comment by thet** [comment]
@mauritsvanrees tnx for fixing!

**Pull request merged**
