### PR TITLE
[6.0] Restore the capability of the resource registry to serve OFS files as resources

### PR DESCRIPTION
**Pull request by thet**
This is the equivalent of #4024 for Plone 6.0

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
Looks like we have very flaky tests here :/

First run failed with:
image

Second:
image


As I do not see any relation to this PR, I'm restarting this test again.

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
Ha, a different error:

image

**Pull request merged**
