### PR TITLE
Fix problem when adding a Plone site with a custom INonInstallable ut…

### PR DESCRIPTION
**Pull request by thet**
…ility without a getNonInstallableProfiles method.

Fixes: #3862.

This PR targets CMFPlone 5.2.x

### CODE REVIEW

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Review by gforcada — APPROVED** [review]
LGTM! 👍🏾

**Review by davisagli — COMMENTED** [review]
I have a doubt about this. Technically if the utility doesn't have a getNonInstallableProfiles method, then it didn't properly implement the INonInstallable interface. If I am trying to add an INonInstallable utility and I make a typo in the method name, this change means that it will silently fail instead of giving a helpful error so that I notice the typo.

**Comment by mauritsvanrees** [comment]
> I have a doubt about this. Technically if the utility doesn't have a getNonInstallableProfiles method, then it didn't properly implement the INonInstallable interface. If I am trying to add an INonInstallable utility and I make a typo in the method name, this change means that it will silently fail instead of giving a helpful error so that I notice the typo.

That is true.  But in the add-ons control panel we already [do the same](https://github.com/plone/Products.CMFPlone/blob/6a8eb557dc8007668dc4a837d41987ab8daf2896/Products/CMFPlone/controlpanel/browser/quickinstaller.py#L83-L89): we check if `getNonInstallableProfiles` is there.
Also, if you do make a typo in the method name, it is usually not so bad: you will get more profiles or products in a list, which probably confuses users, but the package should still work.

It is not clear in the interface, but I intended the two methods to be optional: it is fine to only give a list of profiles or only give a list of products, without needing to provide a dummy method for the other, or inheriting from a base class with dummy methods.

So: LGTM.

**Pull request merged**
