### PR TITLE
Fix resource expression calculation by removing volatile cache

### PR DESCRIPTION
**Pull request by petschki**
continued from here https://github.com/plone/Products.CMFPlone/pull/3844#issuecomment-1945928927

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
I agree with this approach.  While you were working on this, I did some timings as well:

* With the current (6.0.9) way, rendering both resource viewlets takes about 0.002 seconds total.  Expressions do not work.
* With the previous PR it is a bit more due to a [not effective request cache key](https://github.com/plone/Products.CMFPlone/pull/3844#discussion_r1428207568), but with a fix for that it is about the same.  Expressions work, but memory usage increases.
* With the current PR it becomes about 0.005, so it takes longer.  Expressions work.  Memory usage decreases (very) slightly because the volatile cache is gone.  The code is easier.

All in all, I prefer this PR.  Thanks!
Let's wait a bit till others have reviewed it as well.

Side note: most likely, on a production site, the resource viewlets are calculated once on a context, and then the html of the page is cached in Varnish or similar, at least for anonymous visitors.  So it does not matter too much if calculating these viewlets takes a bit longer.

**Review by yurj — APPROVED** [review]
LGTM

This really does what is expected, so +1

Optimizations:
Render time could be improved just caching the single webresource.render() method, using the registry modification time (_RESOURCE_REGISTRY_MTIME), if there's no condition.
99% of the resources has no condition, so we can cache the render() method. This method take most of the time on creating the path. The path does not depends on anything, it is always the same.

Maybe we've to check if the RAM cache here:
https://github.com/plone/Products.CMFPlone/blob/875b899de4671c1870bd4c1fe37bf057952396f1/Products/CMFPlone/resources/webresource.py#L51
for cooked_expressions but I think they are not used at all.

**Review by jensens — APPROVED** [review]

**Comment by jensens** [comment]
@petschki Please do the same for 6.1

**Comment by petschki** [comment]
will do 😉

**Pull request merged**
