### PR TITLE
fix #1811: Remove last legacy Javascript highlight-searchterms.js

### LINKED ISSUE #1811: Remove jquery.highlightsearchterms.js?
It's the last file on plone_ecmascripts folder: https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_ecmascript/jquery.highlightsearchterms.js

Turn it into a pattern? Do we actually even want that? Opinions?

### PR DESCRIPTION
**Pull request by jensens**
and it's skins folder.

* ref #1811
* ref #1801 

- [x] needs upgrade step in ``plone.app.upgrade``:
  - [x] removal of the skin folder from all layers
  - [x] removal from registry

- [x] needs rebuild of ``plone-legacy`` bundle

### CODE REVIEW

**Comment by jensens** [comment]
test fails b/c of #1964

**Comment by cdw9** [comment]
I cherry-picked these commits into the `5.1.x` branch locally, and can confirm that I no longer get the error about the JS. Would love to see this PR get merged in.

**Comment by sunew** [comment]
See https://github.com/plone/plone.app.upgrade/pull/170

**Comment by sunew** [comment]
@jensens upgrade steps in p.a.upgrade done. How do we rebuild the plone-legacy bundle?

**Comment by jensens** [comment]
@sunew IIRC theres an entry in registry ``plone.resources.last_legacy_import``. If you set it to the current date/time the legacy bundle is rebuild automatically. If you need to dig into it, the related code is in ``Products.CMFPlone.resources.browser.*``

**Comment by sunew** [comment]
@jensens thanks!

**Comment by sunew** [comment]
@jensens done see https://github.com/plone/plone.app.upgrade/pull/170

**Comment by sunew** [comment]
@jensens the changelog seems strange after this merge, see https://github.com/plone/Products.CMFPlone/commit/7cefb8f47585422c182e04ae15b08dd2ea456616

(i fixed it now on my backport branch - but needs fixing here too)

**Pull request merged**
