### PR TITLE
Update TinyMCE to 4.3.12 to fix editing bug on Chrome + OSX

### PR DESCRIPTION
**Pull request by MatthewWilkes**
Plone 5.0.x ships with TinyMCE 4.3.4, however there is a known bug on TinyMCE 4.3.<10 that can prevent toolbar buttons working on some browsers. This backports the upgrade to 4.3.12 that's on master to the 5.0.x line.

### CODE REVIEW

**Comment by jensens** [comment]
You can always start a Jenkins test-job on your own to test that your pull request (PR) does not break anything. 

Below click on the link to Jenkins
screenshot from 2016-07-25 11 20 06

**log in** with your Github user - if not already done before.

Paste the full **pull request URL** into the text field (if multiple pull requests need to be combined in one run, then one PR URL per line)

Click on **Build**

Jenkins reports back to the pull request(s) on Github in the status box at the bottom.

In Plone we value a lot our testing suite, so we usually never merge pull requests if they have not been tested by Jenkins first.

**Comment by davilima6** [comment]
@MatthewWilkes, could you please add a changelog?

**Comment by MatthewWilkes** [comment]
Sure thing, just got to find a not-so-busy slot to finish it up.

**Comment by MatthewWilkes** [comment]
Sorry for the slow, @davilima6. Changelog updated.

**Comment by MatthewWilkes** [comment]
Looks like tests are broken on Plone 5 because of migrations.

**Comment by davilima6** [comment]
I think this is safe to ignore. At least there's a comment saying that it fails sometimes :)

**Comment by MatthewWilkes** [comment]
@davilima6 Eric fixed it, was a problem with p.a.upgrade. All passy now!

**Pull request merged**
