### PR TITLE
Fix for quoted search terms

### LINKED ISSUE #3517: searching for phrases within quotes doesn't work
the `munge_search_term` method doesn't work when searching for quoted phrases.

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/search.py

**Reproduce:**

- go to https://6-classic.demo.plone.org/en
- search for `"Welcome to Plone"`
- you get an empty search result

**Background**

the `munge_search_term` returns this for the phrase above:

`'Welcome AND to AND Plone*'`

**Solution**

keep phrases within quotes untouched.

### PR DESCRIPTION
**Pull request by petschki**
fixes #3517

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
Thanks!
Could you add some tests for `munge_search_term` please? It looks like it may be doing the right thing, but it is hard to say from the current tests: they only check how many results there are.
`munge_search_term` could actually be a standalone function. Could be useful for third party code that needs this.
I guess it could also be a `classmethod` and/or `staticmethod`. I can never remember the difference. :-) So feel free to ignore that.

**Comment by petschki** [comment]
@mauritsvanrees I also thought about refactoring as a standalone function so addons coul make `from Products.CMFPlone.browser.search import munge_search_term` and reuse it ... or should we even place it in `Products.CMFPlone.utils` ?

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees I also thought about refactoring as a standalone function so addons coul make `from Products.CMFPlone.browser.search import munge_search_term` and reuse it ... or should we even place it in `Products.CMFPlone.utils` ?

Or `plone.base.utils`? cc @jensens

**Comment by jensens** [comment]
Where else do we need this? It could go into plone.base.utils, since it has zero dependencies. But I would like to avoid adding there random stuff not to be reused. It spreads then logic over multiple packages and makes readability worse.

**Comment by petschki** [comment]
I also would not move it to plone.base.utils. the munge_search_term logic belongs to the search view and therefore the right place is in Products.CMFPlone.browser.search for me ...

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
found a duplicate which could be resolved with plone.base.utils? see https://github.com/plone/plone.app.querystring/blob/master/plone/app/querystring/querybuilder.py#L199

**Review by mauritsvanrees — APPROVED** [review]

**Review by jensens — APPROVED** [review]

**Review by yurj — CHANGES_REQUESTED** [review]

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
One more thing ...

should we add `*` to every word in an unquoted term? so `welcome to plone` would get `welcome* to* plone*` ...

@yurj @mauritsvanrees @agitator @jensens

**Comment by yurj** [comment]
> One more thing ...
> 
> should we add `*` to every word in an unquoted term? so `welcome to plone` would get `welcome* to* plone*` ...
> 
> @yurj @mauritsvanrees @agitator @jensens

Some stop words should be escluded, otherwise ZCTextIndex would search for 'to*' instead of removing it. Beware that the live search and the search clicking on "Search" can differ. For example, on https://6-classic.demo.plone.org/en type "to". Zero results on live search, while clicking on search you will find 5 items...

**Comment by petschki** [comment]
> > One more thing ...
> > should we add `*` to every word in an unquoted term? so `welcome to plone` would get `welcome* to* plone*` ...
> > @yurj @mauritsvanrees @agitator @jensens
> 
> Some stop words should be escluded, otherwise ZCTextIndex would search for 'to*' instead of removing it. Beware that the live search and the search clicking on "Search" can differ. For example, on https://6-classic.demo.plone.org/en type "to". Zero results on live search, while clicking on search you will find 5 items...

there is no difference in generating the search query for `@@search` and `@@ajax_search` both use the same logic (https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/search.py#L239). This difference is because the livesearch only starts when at least 4 characters are given ... results are (and should be) the same.

**Comment by agitator** [comment]
Are there existing stop word lists to build on? 
Not sure if a minimal character approach would work in a multilingual context.

**Comment by petschki** [comment]
whoa ... I've opened pandoras box here 😅

multilingual is a good point. but if I read the docs here correctly, this is done by the ZCTextIndex Lexicon: https://zope.readthedocs.io/en/latest/zopebook/SearchingZCatalog.html#lexicons

so it would be interesting if the `to` in `Welcome to Plone` is removed by the index lexicon ...

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by yurj** [comment]
I think this can be merged, can improved later

**Review by yurj — APPROVED** [review]

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
