### PR TITLE
Implement NewsML feed syndication

### PR DESCRIPTION
**Pull request by hvelarde**
This was ported from collective.syndication and will need to be ported to Plone 5.0.

Refs #151 and #268

### CODE REVIEW

**Comment by vangheem** [comment]
Does this PR address the issues in https://github.com/plone/Products.CMFPlone/pull/151 ?

Mainly need to use check=False in registry settings lookup and also provide an upgrade step in plone.app.upgrade.

Also, a PR for 5.0 would be nice.

**Comment by hvelarde** [comment]
I'm migrating a customer to 4.3 and we need this; @tcurvelo will create the upgrade step and port that to 5.0.

**Comment by vangheem** [comment]
the check=False in forInstance call for https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/syndication/settings.py#L29 is important also.

**Comment by tcurvelo** [comment]
Here is the upgrade: https://github.com/plone/plone.app.upgrade/pull/30
I've tweaked the upgrade made by @jpgimenez. Could someone review it, please?
cc @hvelarde

**Comment by vangheem** [comment]
Looks fine. Merge both as you please.

**Comment by vangheem** [comment]
please make the plone 5 pull request for this also!

**Comment by hvelarde** [comment]
@vangheem please review: https://github.com/plone/Products.CMFPlone/pull/408

there was a conflict on Products/CMFPlone/browser/syndication/templates/search-rss.pt

**Pull request merged**
