### PR TITLE
[WIP] #1480 Bug fix for full text search

### PR DESCRIPTION
**Pull request by terapyon**
- [x] Modify text search function for bug fix
- [ ] Modify test code
- [ ] Write HISTRY.txt

### CODE REVIEW

**Comment by terapyon** [comment]
Why is it  Agreement verifier NG? I'm Contributor for Plone core.

**Comment by mauritsvanrees** [comment]
Maybe the checker complains about commit https://github.com/plone/Products.CMFPlone/pull/1650/commits/33579996126c2bf48cd601325f10c8d7e2e1531f which has only a name, not an email address. It is a merge commit. I guess this might be fixed when you rebase the branch so you do not need a merge commit.

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Comment by terapyon** [comment]
I will check this issue.

**Pull request closed without merging**
