### PR TITLE
prevent breaking Plone when TinyMCE settings contain invalid JSON

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
http://jenkins.plone.org/job/pull-request-5.0/467/

**Comment by thet** [comment]
The form should actually validate these settings. But this is another story. Will merge when green.

**Comment by petschki** [comment]
so this should do the trick ... all JSON fields in TinyMCE settings form are validated and if someone changes values via genericsetup or registry.xml they're passed ...

**Comment by petschki** [comment]
http://jenkins.plone.org/job/pull-request-5.0/468/

**Comment by petschki** [comment]
http://jenkins.plone.org/job/pull-request-5.0/497/
@vangheem ready to merge

**Comment by thet** [comment]
Tnx!

**Pull request merged**
