### PR TITLE
build resources for latest path criteria improvements

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
Build here: http://jenkins.plone.org/job/pull-request-5.0/650/

**Comment by vangheem** [comment]
@obct537 A couple plone.app.contenttypes robot failures.

**Comment by vangheem** [comment]
test success here: http://jenkins.plone.org/job/pull-request-5.0/651/

**Comment by gforcada** [comment]
@vangheem @obct537 sorry seems that the problem is actually on this merge.

**Comment by obct537** [comment]
@gforcada I just re-ran the tests locally with all the merges in place, and they all passed? Should we possibly re-run jenkins?

**Comment by gforcada** [comment]
@obct537 you can run jenkins jobs as many times as you wish, specially safe are the pull request jobs.

When it comes to robot failures on jenkins usually is a timing issue. You can look at the screenshot automatically generated, maybe is giving you a hint: http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/3596/robot/report/robot_log.html#s1-s10-t1 click on *KEYWORD: Selenium2Library.Capture Page Screenshot*

**Pull request merged**
