### PR TITLE
re-add missing dashboard menu item as per #1132

### PR DESCRIPTION
**Pull request by tkimnguyen**
for #1132

### CODE REVIEW

**Comment by davilima6** [comment]
Thanks, @tkimnguyen. I don't think it's a blocker but it'd be nice to add or update tests so we avoid regressing again. Any idea on where those would go? Couldn't find.

**Comment by tkimnguyen** [comment]
@davilima6 ah, good idea but I don't know either

**Comment by davisagli** [comment]
Since this is a change to a GenericSetup profile (i.e., something that will make a persistent change to the database), we also need an upgrade step.

**Comment by davisagli** [comment]
Re tests, I would add a simple functional test in this package or in plone.app.portlets which logs in and confirms that there's a Dashboard link to click.

**Comment by tkimnguyen** [comment]
@davisagli would something like this in tests/testActionsTool.py suffice?

```
    def testDashboardActionExists(self):
        actions = self.actions.listActions()
        self.assertTrue('dashboard' in [a.id for a in actions])
```

I was looking for a good place to put an upgrade step but couldn't find one in this package - any suggestions?

**Comment by davisagli** [comment]
That'll work...it doesn't seem quite like the right place, since the rest of the tests there are about Plone's additional functionality for the CMF action tool rather than tests of how the Plone profile configures actions, but I don't see an obvious better place to put it either.

Upgrade steps go in plone.app.upgrade.

**Comment by jensens** [comment]
this was fixed afaict

**Pull request closed without merging**
