### PR TITLE
Ship with plone.restapi.

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.2/160/

**Comment by tisto** [comment]
https://jenkins.plone.org/job/pull-request-5.2/1641/console

**Comment by hvelarde** [comment]
@plone/framework-team just a friendly reminder: this PLIP must not be accepted until this blocker is fixed: https://github.com/plone/plone.rest/issues/73

**Comment by tisto** [comment]
@jensens FYI: I added the dependency to the "Plone" pkg: https://github.com/plone/Plone/pull/13

**Pull request closed without merging**
