### PR TITLE
Remove `propertiestool` import step and usage of `portal_properties`.

### PR DESCRIPTION
**Pull request by mauritsvanrees**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Review by ale-rt — APPROVED** [review]
LGTM, waiting for the other PRs to be merged and the test to be green before merging

**Comment by mauritsvanrees** [comment]
Continue on this once https://github.com/plone/Products.PlonePAS/pull/89 is green and merged.

**Comment by mauritsvanrees** [comment]
I think all core code that used `portal_properties` has been removed, merged and released, and dist.plone.org updated.  So we can try again:

@jenkins-plone-org please run jobs

In `plone.app.upgrade` I [added a branch](https://github.com/plone/plone.app.upgrade/tree/maurits-remove-properties-tool-if-empty) to remove the properties tool if it is basically empty.  That would be the nice way.
But we could also remove it unconditionally, and remove the remaining classes here in `Products.CMFPlone`.
I have no time to continue on this the next two weeks.

**Review by gforcada — APPROVED** [review]

**Review by davisagli — APPROVED** [review]

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
