### PR TITLE
fix: add pat-base to registry

### PR DESCRIPTION
**Pull request by Gagaro**
This fix this issue: https://github.com/plone/mockup/issues/589

### CODE REVIEW

**Comment by vangheem** [comment]
This commit might need to be coupled with a new version of patternslib that mockup is using now. See https://github.com/plone/mockup/blob/master/bower.json#L20

Then see, https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/static/bower.json#L22

\cc @jcbrand

**Comment by jcbrand** [comment]
We need a new release of Patternslib. I'll do so ASAP and let you guys know here.

**Comment by jensens** [comment]
Adding values to registry usually needs an upgrade step to introduce the new value to old instances. Please check if one is needed.

**Comment by Gagaro** [comment]
How should I add an upgrade step for this profile if needed ? I don't see any.

**Comment by jensens** [comment]
Upgrade steps are in https://github.com/plone/plone.app.upgrade 
I'am really not sure if this type of change needs an upgrade steps. Maybe someone else may enlight us. But registry tends to need upgrade steps for any addition, so I'd double check.

**Comment by jcbrand** [comment]
BTW, I've released Patternslib 2.0.11 and updated mockup to use this version.
https://github.com/plone/mockup/commit/87133c2ae919fdd68cf7e181323f7e65a969d5ca

**Comment by Gagaro** [comment]
I added an upgrade step: https://github.com/plone/plone.app.upgrade/pull/56

**Comment by Gagaro** [comment]
Thanks for the release @jcbrand :+1:

**Comment by jensens** [comment]
@jcbrand I'am a bit lost with this one, may you have a look at this PR and the one in plone.app.upgrade and merge if all is fine?

**Comment by jcbrand** [comment]
@jensens: Yes will do. I'm also looking at this one: https://github.com/plone/Products.CMFPlone/pull/1121

**Comment by jcbrand** [comment]
This pull request has been merged into the pull request #1121. Closing here.

**Pull request closed without merging**
