### PR TITLE
Fix random fails in test_querystring.robot

### PR DESCRIPTION
**Pull request by wesleybl**
Check if select criteria is visible after clicking in body.

See: https://jenkins.plone.org/job/plone-6.0-python-3.7-robot-chrome/689

### CODE REVIEW

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
I started the jobs several times and saw no errors in `test_querystring.robot`. So hopefully this has solved the problem.

**Comment by ale-rt** [comment]
It surprises me that we need to `Click Element  css=body` in the first place. 
I will make an exploratory PR to see if just removing that line makes the PR pass consistently.

**Comment by ale-rt** [comment]
See #3365

**Comment by ale-rt** [comment]
> It surprises me that we need to `Click Element css=body` in the first place. I will make an exploratory PR to see if just removing that line makes the PR pass consistently.

That fails horribly :)

**Review by ale-rt — APPROVED** [review]

**Pull request merged**
