### PR TITLE
Cleanup of PLIP #1734

### PR DESCRIPTION
**Pull request by thet**
Followup of https://github.com/plone/Products.CMFPlone/issues/1734

To be merged together:

https://github.com/plone/Products.CMFPlone/pull/2068
https://github.com/plone/plone.app.content/pull/131
https://github.com/plone/plone.app.contenttypes/pull/410
https://github.com/plone/plone.portlet.collection/pull/17
https://github.com/plone/plone.app.event/pull/258
https://github.com/plone/plone.app.portlets/pull/99
https://github.com/plone/mockup/pull/774

### CODE REVIEW

**Comment by thet** [comment]
@fgrcon I hope you're ok with this after-PLIP cleanup. Sorry for not stepping in earlier and reviewing. Instead I did the review afterwards and fixed what I thought should be fixed myself. as your PLIP changes a lot, I thought it's worth to do it...

**Comment by fgrcon** [comment]
see https://github.com/plone/mockup/pull/774#issuecomment-307959214 and discussion above.

**Comment by gforcada** [comment]
@thet changelog please 😄

**Comment by thet** [comment]
@gforcada there is already one. This PR is just a follow-up of #1734:

```
- add registry settings for thumb and icon handling in tables, lists and portlets https://github.com/plone/Products.CMFPlone/issues/1734 (PLIP) recompiled bundle plone-logged-in requires upgrade step (reapply profile) [fgrcon]
```

**Comment by thet** [comment]
tnx for approving. I'm gonna merge it to, so that these changes come ASAP into core before anyone is using the old variable names.

@fgrcon if you already deployed sites based on the old var names and run into troubles, talk to me.

**Pull request merged**
