### PR TITLE
If a bundle does not provide any resources, do not attempt to compile it

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
tests: http://jenkins.plone.org/job/pull-request-5.0/912/

**Comment by vangheem** [comment]
@gforcada looks like we have problems with jenkins? ^^

**Comment by gforcada** [comment]
@vangheem yes, there's a weird corner case: https://github.com/plone/jenkins.plone.org/issues/135

I re-run this job again, it should be fine now.

**Comment by jensens** [comment]
looks like this one has some problems left

**Comment by vangheem** [comment]
well, let's try testing again... Pretty sure the failures are't related to change: http://jenkins.plone.org/job/pull-request-5.0/973/

**Pull request merged**
