### PR TITLE
PLIP 3339: Replace z3c.autoinclude with plone.autoinclude.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Note: `includeDependencies` is no longer supported.

Part of PLIP #3339.
Used by this [PLIP config](https://github.com/plone/buildout.coredev/blob/6.0/plips/plip-3339-plone-autoinclude.cfg).

### CODE REVIEW

**Comment by ale-rt** [comment]
I am reviewing this PR.

My plan is to first open a PR to buildout.coredev to include:
```
[sources]
plone.autoinclude = git ${remotes:plone}/plone.autoinclude.git pushurl=${remotes:plone_push}/plone.autoinclude.git branch=main

[versions]
plone.autoinclude = 1.0.0a2
```

IMO that can be done even now  without causing troubles to anyone.
After that I will update this branch and start a regular jenkins test run.

CC @plone/framework-team

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@plone/framework-team for me this is good to be merged. 
Given:
- https://github.com/plone/buildout.coredev/pull/755
was already merged

Merging this will close the PLIP #3339.

See my review: https://github.com/plone/buildout.coredev/pull/756/files

**Comment by ale-rt** [comment]
@plone/framework-team if nobody speaks against it I will merge this PR today.

**Comment by tisto** [comment]
@ale-rt go go go!

**Review by rodfersou — APPROVED** [review]
LGTM

**Review by avoinea — APPROVED** [review]

**Pull request merged**
