### PR TITLE
remove zope mention in logout form

### PR DESCRIPTION
**Pull request by tkimnguyen**

### CODE REVIEW

**Comment by hvelarde** [comment]
do you mind squashing this?

**Comment by tkimnguyen** [comment]
I made this new PR after squashing (sorry, my first time trying to squash things). https://github.com/plone/Products.CMFPlone/pull/1463

**Comment by tkimnguyen** [comment]
Oops, looks like @jensens already merged!

**Comment by jensens** [comment]
and squashed. i just invested the 2 minutes to get this merged :)

**Comment by tkimnguyen** [comment]
Yeah, took me a bit to figure out how to squash

**Pull request merged**
