### PR TITLE
Do not truncate sortable_title [5.2.x]

### LINKED ISSUE #3690: Sortable title cuts the title without a valid reason
In Plone 5.2 and also in 6 the sortable_title index is a FieldIndex in the catalog used to sort contents based on titles. But the sortable_title method in portal_catalog just cuts the title in the middle if the title is longer that 40 chars.

Master:
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/CatalogTool.py#L165-L184

https://github.com/plone/Products.CMFPlone/blob/5.2.x/Products/CMFPlone/CatalogTool.py#L190-L211

Is this behavior intended? And if so why?

### PR DESCRIPTION
**Pull request by erral**
Fixes #3690 for Plone 5.2.x

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Review by ale-rt — COMMENTED** [review]
Thanks for that :)
I am not sure I want to see this change in Plone 5.2.

CC @plone/release-team @plone/framework-team

**Comment by erral** [comment]
Yeah... I have just seen the failures...

My failure was in a Plone 5.2 site, that's why I added the PR to this too.

**Comment by erral** [comment]
I am closing this since it is not acceptable for 5.2. 

If you need to fix this in your Plone 5.2.x, just patch the `Products.CMFPlone.CatalogTool.MAX_SORTABLE_TITLE` to set to a bigger limit or write a new indexer for `sortable_title`

**Pull request closed without merging**
