### PR TITLE
Remove nonfolderish_tabs. Show all except File and Image in navigation

### PR DESCRIPTION
**Pull request by pbauer**
See https://github.com/plone/Products.CMFPlone/issues/785

### CODE REVIEW

**Comment by pbauer** [comment]
Jenkins: http://jenkins.plone.org/job/pull-request-5.0/338/

**Comment by pbauer** [comment]
test are green

**Comment by tisto** [comment]
@pbauer I was under the assumption that the nonfolderish_tabs setting is about the global navigation tabs, not about the portlet navigation. Those are two different things. I usually turn the nonfolderish_tabs setting off for all my Plone sites and use the displayed_types setting to control the portlet navigation.

**Comment by pbauer** [comment]
Wow. I did not know that. So ```nonfolderish_tabs ``` is only used for the tabs whereas ```displayed_types```is used for tabs and navigation-portlets. 
Would it be good to have ```displayed_types``` only used in the navigation-portlets and a new setting ```types_displayed_in_tabs``` only used for the tabs? I still think that the distinction between folderish and no-folderish is not really useful here (especially since all types created ttw are folderish). 

My proposed defaults would be:
types_displayed_in_tabs: All default types except files and images
displayed_types: All default types

**Comment by tisto** [comment]
I think so, yes. I still think making TTW types folderish by default is a big mistake. This will confuse the hell out of people and moving partly into that direction is by far the worst thing we could do in my opinion. Do it right or don't do it at all, everything else will be a disaster.

A new setting is not necessary in my opinion, if we stick with folderish/non-folderish types in Plone 5.0, and this is what the FWT decided. Especially since we are talking about release candidates now.

**Comment by pbauer** [comment]
Ok, then we'll simply keep the setting that is now on the registry and postopne this change to a later time. I clarified the wording for the navigation-control-panel here: https://github.com/plone/Products.CMFPlone/pull/1022

@tisto Your rant about the default for folderish types in the dexterity-control-panel is but a little out of place here. You should discuss that in the FWT if you think it will be a disaster.

**Comment by tisto** [comment]
@pbauer I agree. We discussed this in the FWT and made a decision to stick with folderish/non-folderish types for 5.0. This decision also means that we are not going to sneak in small changes towards that direction (in my personal opinion).

**Comment by jensens** [comment]
yes, i agree with @tisto, keep the setting. yesterday it worked ;) as i manually tested it. in future we may have a different definition of "folderish", but now its too early to make changes here.

**Pull request closed without merging**
