### PR TITLE
add Collection to the default_page_types setting

### PR DESCRIPTION
**Pull request by erral**
See https://github.com/plone/plone.app.content/issues/182

Merge together: https://github.com/plone/plone.app.content/pull/184

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
The combined test is green : https://jenkins.plone.org/job/pull-request-5.2/586/

**Comment by erral** [comment]
Ups, I copied-over the file and put it in the wrong folder.

Regarding the upgrade step, it might be useful indeed.

I will try to do the upgrade step and report here.

**Comment by erral** [comment]
I prepared this: https://github.com/plone/plone.app.upgrade/pull/217 I think this is my first time with an upgrade step, so a review will be welcomed :)

**Comment by mauritsvanrees** [comment]
Ah, right, an upgrade step is needed. I have added a review in your PR.

**Pull request merged**
