### PR TITLE
4.3.x Hotfix20200121 Password

### PR DESCRIPTION
**Pull request by gotcha**
Password strength checks were not always checked

see #3021 

better branch name, supercedes #3022

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by gotcha** [comment]
@mauritsvanrees Thanks for the tests !

What is the practice for changelog ?

**Comment by mauritsvanrees** [comment]
No. But you can do `3021.bugfix.1`, `3021.bugfix.2`, etc.

**Comment by gotcha** [comment]
@mauritsvanrees Should I squash commits before merging ? a single commit might be easier to cherry-pick on other branches.

**Comment by mauritsvanrees** [comment]
There were [two test failures](https://jenkins.plone.org/job/pull-request-4.3/30/testReport/). One is actually good: code was trying to set a password of three characters, which worked until now, but not anymore. I updated the test and force pushed it.
The other is a failing robot test. It has been a while since I have run robot tests locally, and currently it does not work, so I can't check it.
Maybe it is flaky:
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
