### PR TITLE
Updated jqtree to 1.4.1 to autoscroll for items when dragging.

### PR DESCRIPTION
**Pull request by b4oshany**

### CODE REVIEW

**Comment by datakurre** [comment]
Depends on https://github.com/plone/mockup/pull/781

**Comment by thet** [comment]
LGTM

**Comment by seanupton** [comment]
@thet @datakurre @b4oshany does this require that we rebuild compiled mockup assets (and which bundle?) to use this outside of development mode?  I get the sense that this might be a remaining loose end, but I am not sure.  Let me know, I am happy to help if so.

**Comment by datakurre** [comment]
@seanupton I believe that this is only used in thememapper bundle. Oshane needs this for drag and drop support in filemanager pattern used by thememapper.

**Comment by seanupton** [comment]
@datakurre thanks for clarifying.

**Pull request merged**
