### PR TITLE
Fix actions

### PR DESCRIPTION
**Pull request by jensens**
After adding explicit deprecation messages to before only soft-deprecated methods on ploneview, this step is needed.
I expect a minor performance improvement as well.
Anyway, this here helps only on new sites, an upgrade step is needed too.

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
As this needs an upgrade step, is it enough to take a copy of `actions.xml` with the non-changed fields removed? It could then overwrite customizations. Does somebody have a better idea?

cc @mauritsvanrees @petschki @ale-rt @cekk

**Review by mauritsvanrees — APPROVED** [review]
LGTM

**Comment by mauritsvanrees** [comment]
> As this needs an upgrade step, is it enough to take a copy of `actions.xml` with the non-changed fields removed? It could then overwrite customizations. Does somebody have a better idea?

That is the right approach.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
> As this needs an upgrade step, is it enough to take a copy of `actions.xml` with the non-changed fields removed? It could then overwrite customizations. Does somebody have a better idea?
> 

This could theoretically wipe out user customizations...

I know it is more tedious, but IMO the right approach is to cicle the portal actions objects and replace `url_expr` with the new value if and only if it matches the old value.

**Comment by jensens** [comment]
> This could theoretically wipe out user customizations...

As I mentioned above. But trust my release manager here (see above).

**Pull request merged**
