### PR TITLE
Fix advanced search issue #3007 

### PR DESCRIPTION
**Pull request by frapell**

### CODE REVIEW

**Comment by frapell** [comment]
So, it turns out that ZCatalog will specifically check if the index is a dict or not in https://github.com/zopefoundation/Products.ZCatalog/blob/e751eff05374e7f8b39d59b9b9e16e33fab47e11/src/Products/ZCatalog/query.py#L68

If it's not, it will just copy the index right away into the keys, causing the `TypeError: unhashable type: 'record'`
And this is because the `created` parameter is not a dict, but a `ZPublisher.HTTPRequest.record`

This fix will cast the `record` type as `dict`, which solves the issue.

This is a fix for issue https://github.com/plone/Products.CMFPlone/issues/3007

**Comment by frapell** [comment]
@jenkins-plone-org please run jobs

**Comment by ericof** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@frapell in fact, this error occurs with any search that has the `query` key.

For example the url below also fails:

http://localhost:8080/Plone/@@search?end.query:record:list:date=2022-2-2+00%3A00%3A00&end.range:record=min

So the fix must be made to all parameters that have the `query` key, not just the `created` parameter.

**Comment by wesleybl** [comment]
In fact, since dictionaries in url are turned into record, maybe the best solution is to test:

```python
if isinstance(param, dict) or isinstance(param, record):
```
in:

https://github.com/zopefoundation/Products.ZCatalog/blob/e751eff05374e7f8b39d59b9b9e16e33fab47e11/src/Products/ZCatalog/query.py#L68

See: https://github.com/plone/Products.CMFPlone/pull/3012#issuecomment-570630842

@frapell @ericof @ale-rt opinions?

**Comment by frapell** [comment]
@wesleybl It's been 2 years since this fix, so I don't fully remember, and I don't know what would be the proper fix, however on a first glance it does look like it should be for the `@@search` view to properly convert `records` into `dicts`

**Pull request merged**
