### PR TITLE
Update the link to the new PLIP page

### PR DESCRIPTION
**Pull request by stevepiercy**
See https://github.com/plone/documentation/pull/1671

### CODE REVIEW

**Comment by stevepiercy** [comment]
Let's skip Jenkins for this trivial internal change.

**Comment by stevepiercy** [comment]
@plone/release-team please update your issue templates. I did this one and Volto only.

**Review by mauritsvanrees — APPROVED** [review]
Thanks, LGTM.

> @plone/release-team please update your issue templates. I did this one and Volto only.

I see [a few issue templates](https://github.com/search?q=org%3Aplone+path%3AISSUE_TEMPLATE&type=code) but I think only the `plone.classicui` one needs to be updated with this link.  I will do so.

**Comment by mauritsvanrees** [comment]
Oops, did I really forget to merge this after I approved?  Sorry.

**Comment by stevepiercy** [comment]
lol, I assumed you went on to fix `plone.classicui`, no worries.

**Pull request merged**
