### PR TITLE
Fix accessibility info

### PR DESCRIPTION
**Pull request by yurj**
Use label_site_administration instead of label_site_admin because of the missing article. Must be checked over other languages but italian and english would be ok and the fix is the same of pull https://github.com/plone/Products.CMFPlone/pull/3397

### CODE REVIEW

**Comment by yurj** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
Why is this needed?

**Comment by yurj** [comment]
> Why is this needed?

In Italian I get:
"Il sito usa assistive technology, come i ruoli WAI-ARIA, nel rispetto delle migliori pratiche definite ad oggi. In ogni caso il sito, gli standard e i contenuti variano nel tempo. Se questo sito web non passa correttamente la validazione, per favore contatta l'l'amministrazione del sito." <- there's a double l'l'

with the commit, I get:
"Il sito usa assistive technology, come i ruoli WAI-ARIA, nel rispetto delle migliori pratiche definite ad oggi. In ogni caso il sito, gli standard e i contenuti variano nel tempo. Se questo sito web non passa correttamente la validazione, per favore contatta l'amministrazione del sito." <- no double

The same fix was done in https://github.com/plone/Products.CMFPlone/pull/3397 with the same scenario. Other languages seems already ok but the Italian has this article with the apostrophe in front of feminine nouns. I don't know if this is the right fix or the right place to fix it.

**Review by erral — APPROVED** [review]

**Comment by erral** [comment]
@mauritsvanrees should we merge this?

**Comment by mauritsvanrees** [comment]
I wondered what "article" meant, but I slowly realised this means: "the" or "an".

This change is not good for Dutch. There we have these translations:

```
msgid "label_site_admin"
msgstr "websitebeheerder"

msgid "label_site_administration"
msgstr "Website beheer"

msgid "description_validation"
msgstr "... de ${site_admin}."
```

Here, "de" is a Dutch article.

So with the code from master we get: "...de websitebeheerder", which is correct Dutch.
With your code we get "de Website beheer", which is wrong. So I would need to edit the Dutch `description_validation` message to remove the "de" article. Or maybe replace "de" with another article "het", but that reads a bit awkward.

So: please do not merge this. It is bad for one language, and maybe more.

Instead I would say, just edit the Italian po file: instead of ending the `description_validation` translation with `contatta l'${site_admin}.`, let it end with  `contatta ${site_admin}.`

**Comment by yurj** [comment]
I agree, can you also check https://github.com/plone/Products.CMFPlone/pull/3397 if it has to be reverted/changed too?

**Comment by mauritsvanrees** [comment]
> I agree, can you also check #3397 if it has to be reverted/changed too?

Yes, a revert for this would be better for Dutch, although I should change one Dutch related message anyway.

The danger is that some translators have already adapted the new translations to work better together, and they might need to change them again after we revert this. :-/

Also, for me "site administration" sounds both like an activity ("I do site administration") and like a person or team ("I am the site administration" or "I belong to the site administration"). If you just translate the po files without context, you don't really know which of the two it is. That makes it difficult.

I wonder if there are many po files where the translations for these two strings are different. If they are only a few, then we could also pick either `label_site_admin` or  `label_site_administration` and use only that one everywhere.

**Pull request closed without merging**
