### PR TITLE
Remove adapter for index location

### LINKED ISSUE #3347: Index location doesn't work for Dexterity content
### What I did:

- I created a Dexterity type with the `location` field.
- I created a `location` index of type ZCTextIndex in portal_catalog.
- I created an object of the content type that had the `location` field.

### What I expect to happen:

Hope the catalog indexing the location field of the object created in `location` index.

### What actually happened:

The `location` field is not indexed.

### What version of Plone/ Addons I am using:

**Plone: 5.2.6**

This is because Plone define an `location` index but uses the `getField` method, which is for Archetype:

https://github.com/plone/Products.CMFPlone/blob/f2d8813d0a1b82cd8ef3adfc0554609452b1e51c/Products/CMFPlone/CatalogTool.py#L258-L260

As Archetype is at the end of its life, I think this index can be removed, or set to Archetype only.

### PR DESCRIPTION
**Pull request by wesleybl**
Adapter for index `location` only worked with Archetypes content, as it used `getField` method. This caused that, when an `location` index  was created in the catalog, the indexing would not work for Dexterity contents, since the adapter trie to use the `getField` method on a Dexterity content.

Fixes #3347 in Plone 6

### CODE REVIEW

**Review by ale-rt — APPROVED** [review]
Top!

**Comment by wesleybl** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
@ale-rt do you know why the `robot-mister` did not pass this PR? Does it take a while to get through?

**Comment by ale-rt** [comment]
I think there is a problem somewhere in jenkins, if you check: https://jenkins.plone.org/job/pull-request-6.0-3.7/661/console

You can read:
```
Got pbr 5.8.0.
Version and requirements information containing pyparsing:
  [versions] constraint on pyparsing: 3.0.6
  Requirement of httplib2: pyparsing<3,>=2.4.2
  Requirement of packaging: pyparsing!=3.0.5,>=2.0.2
While:
  Installing releaser.
Error: The requirement ('pyparsing<3,>=2.4.2') is not allowed by your [versions] constraint (3.0.6)
Build step 'Virtualenv Builder' marked build as failure
```

I have no idea for the moment.

CC @plone/testing-team

**Comment by ale-rt** [comment]
CC @plone/ai-team

**Comment by wesleybl** [comment]
> I think there is a problem somewhere in jenkins, if you check: https://jenkins.plone.org/job/pull-request-6.0-3.7/661/console

@ale-rt I run buildout locally and also saw this error.

I think it was caused by: https://github.com/zopefoundation/Zope/commit/adacc419e7ba09c1c17a2b43256432b315124923

Look: https://github.com/plone/buildout.coredev/commit/551314149ed6ceda923c2ff48e42311dab034c55

CC @mauritsvanrees

**Comment by mauritsvanrees** [comment]
I have fixed it by upgrading `httplib2` to the latest version.

We indeed always checkout Zope. Bad about this is that we sometimes will suddenly run into a problem like this.  Good about this is that we run into it *now* instead of after a Zope release.

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
Python 3.9 job failed with an unrelated robot test.

I create PR #3362  to fix this failed test.

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by wesleybl** [comment]
> We indeed always checkout Zope. Bad about this is that we sometimes will suddenly run into a problem like this. Good about this is that we run into it now instead of after a Zope release.

@mauritsvanrees Is this Zope master pin only until Plone 6 is released? What will happen when Plone 6 is released? You probably don't want plone-6.0.cfg to point to the Zope master. Pointing to the latest Zope release doesn't seem right either, since there may be new pins in the master. Are you going to point to a specific commit?

**Comment by mauritsvanrees** [comment]
The Zope version in a Plone release will always be a real Zope release on PyPI, not some checkout. If too much has happened since the last Zope release, we will have to check which packages may be newer in the Zope versions.

**Pull request merged**
