### PR TITLE
Use behavior-names instead of python-paths in types-controlpanel

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Review by ale-rt — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
This breaks two related robot tests that probably still expect the old names somewhere.

**Comment by jensens** [comment]
+1 for the change - just tests needs fixing as well.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
tests are fixed but `pull-request-6.0-3.6` doesn't exist on jenkins.plone.org but is required here ... @mauritsvanrees @pbauer why that?

**Comment by mauritsvanrees** [comment]
> tests are fixed but `pull-request-6.0-3.6` doesn't exist on jenkins.plone.org but is required here ... @mauritsvanrees @pbauer why that?

I think this is an error in the `mr.roboto` config on the Jenkins server. Originally we tested 6.0 on 3.6 but not anymore.
@fredvd Can you check the config on the server?

**Comment by ale-rt** [comment]
If the PR was created before the Python 3.6 job was removed the check will stick forever.

This was the case also for https://github.com/plone/Products.CMFPlone/pull/2612.

If you really want to run it you still can:
- visit https://jenkins.plone.org/job/pull-request-6.0-3.6/
- login
- click "Build with Parameters"
- enter this PR URL (https://github.com/plone/Products.CMFPlone/pull/3294)
but it is somewhat pointless.

If it fails the PR will still be good for being merged if the other checks are green :)

**Comment by ale-rt** [comment]
Well also new PRs have the Python 3.6 job... I added an issue: https://github.com/plone/Products.CMFPlone/issues/3318

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
