### PR TITLE
Fix false positive `missing_packages` in `@@plone-upgrade`

### LINKED ISSUE #4015: `@@plone-upgrade` page claims false missing packages
There are packages which defines multiple installable profiles in subfolders. See `collective.collectionfilter` for example.

The upgrade page tries to find a distribution for a profile name but it fails for those "sub" profiles (though they are installed) and shows the following warning:

Bildschirmfoto 2024-09-24 um 08 59 25

### PR DESCRIPTION
**Pull request by petschki**
fixes #4015

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by davisagli — APPROVED** [review]
First thought: this might be dangerous, since importing modules can have side effects.

Second thought: If the profile was installed, then it's very likely the module was already imported by ZCML anyway.

Third thought: this is probably more correct even without submodules, since the name of a Python distribution does not necessary match the name of the packages inside.

**Review by mauritsvanrees — COMMENTED** [review]
This seems fine.  But how about trying both ways?

```
            try:
                distribution(package)
            except PackageNotFoundError:
                # profiles can live in submodules of packages.
                # check if we can import the module namespace
                try:
                    import_module(package)
                except ModuleNotFoundError:
                    missing.append(package)
```

This might catch some other corner cases, although I can't really say which ones. :-)

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]

**Pull request merged**
