### PR TITLE
[5.2] Improve tests for the workflow tool method listWFStatesByTitle

### PR DESCRIPTION
**Pull request by ale-rt**
Test also the filter_similar option.
Use a dummy setup (makes life easier for tests and simplify the life of people who are changing for some reason the Plone workflows)

Refs #3032

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
Robot failure in branch 5.2 do not appear related.
Please also merge with #3038

**Comment by mauritsvanrees** [comment]
I have merged both this 5.2 PR and the similar 6.0 PR. Thanks!

**Pull request merged**
