### PR TITLE
Sub-sort language by label, not language code when adding a site

### PR DESCRIPTION
**Pull request by instification**
Currently, when adding a site the languages are sorted alphabetically and then subsorted by their language code. This means the labels are not alphabetically sorted and is confusing when creating a site.

For example English (United Kingdom) comes before English (Granada) because en_gb < en_gd.

This pr subsorts by label (lowercase) to provide an alphabetical list of languages.

### CODE REVIEW

**Comment by instification** [comment]
http://jenkins.plone.org/job/pull-request-5.0/464/

**Comment by instification** [comment]
@thet please look!

**Comment by instification** [comment]
@thet have pulled latest changes from master and re-run the jenkins job (passed): http://jenkins.plone.org/job/pull-request-5.0/518/

Would you be ok to look at this or pass it to somebody else?

I think it's quite important from a ux perspective that users are shown a sorted list of languages to choose from.

**Comment by gforcada** [comment]
Yes, it makes much more sense to sort like that! Merging.

**Comment by thet** [comment]
Tnx for the fix! There is also the language control panel, where this fix eventually should be applied.

**Pull request merged**
