### PR TITLE
Remove dependency on CMFUid.

### PR DESCRIPTION
**Pull request by jensens**
Seems unused. Let the tests decide.

### CODE REVIEW

**Comment by jensens** [comment]
see also #1343

**Comment by gforcada** [comment]
At least needs an upgrade step and there are some traces of it in
cmfeditions
El dia 28/05/2016 6:46, "Jens W. Klein" <notifications@github.com> va
escriure:

**Comment by gforcada** [comment]
I was looking into it, as the PLIP for collective.indexing got quite a lot of errors after rebasing my branch on top of CMFUid 2.3 instead of 2.2 and trying to clean CMFEditions from CMFUid traces lead me to ``portal_historyidhandler`` which is at least being used by plone.app.iterate.

I will stop here as that's a bit too much for a small cleanup, but it feels that CMFUid 2.3 branch is not ready at all and probably we stick with 2.2 and try to get rid of it instead of updating it.

I would need a separate PLIP though.

**Comment by jensens** [comment]
Phew. CMFEditions should be changed to use ``plone.uuid``.  The tool in CMFEditions is deprecated anyway and can be removed. If anyone relies with addon code on CMFUid it can be installed anyway as an addon.

TODO:

- [ ] make this a plip
- [ ] Change CMFEditions to get its UIDs from ``plone.uuid`` (ensure old UUIDs are read)
- [ ] Remove CMFEditions old deperecated BBB uid tool.
- [ ] Conditional imports in plone.app.upgrade for CMFUid
- [ ] Upgrade step in plone.app.upgrade to remove all traces of CMFUid

**Pull request closed without merging**
