### PR TITLE
Fix problem when adding a Plone site with a custom INonInstallable ut…

### PR DESCRIPTION
**Pull request by thet**
…ility without a getNonInstallableProfiles method.

Fixes: #3862.

This PR targets CMFPlone master

### CODE REVIEW

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
@thet Can you make a PR for 6.0.x as well?  Then it can go into 6.0.8 that I am preparing now.

**Comment by thet** [comment]
will do!

**Comment by thet** [comment]
@mauritsvanrees done: https://github.com/plone/Products.CMFPlone/pull/3868

**Pull request merged**
