### PR TITLE
[5.2] The portal catalog will not try to index itself anymore

### PR DESCRIPTION
**Pull request by ale-rt**
Refs #3312

### CODE REVIEW

**Review by tisto — APPROVED** [review]

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
I tested it, and it helps, thanks.

Two Jenkins jobs have failures that should be unrelated. I am running them again to be sure. Can be merged when green.

**Comment by thet** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@mauritsvanrees The yellow test is obsolete. I think this is good to be merged but I have not the power to click the button while there is a test pending

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees The yellow test is obsolete. I think this is good to be merged but I have not the power to click the button while there is a test pending

Ah, there were some outdated settings in the branch protection rules. I probably already updated them for 6.0 a while ago, but did not think of 5.2.x. Or that was in a different project. Anyway, fixed.

Now all checks pass. Thanks!

**Comment by ale-rt** [comment]
Thanks to you!

**Pull request merged**
