### PR TITLE
[a11y] Added role attribute for portalMessage (5.1.x)

### PR DESCRIPTION
**Pull request by nzambello**
Screen readers could now see and read correctly alerts/status messages.

### CODE REVIEW

**Comment by gforcada** [comment]
Thanks for **all** these pull requests!!

At least for this one, would you mind forward porting it to master branch too? Or did I miss it? 😅

**Comment by nzambello** [comment]
@gforcada Hi, I created another PR for `master` branch.
The other PRs are for `master` branches of their repos.

**Comment by gforcada** [comment]
Thanks!  I will try my best to review them as soon as I have some time, I'm on vacations now

**Comment by gforcada** [comment]
All merge requests, but the ones on this repository, have been merged :tada: 
The ones in this repo need a minor fix: since a few months ago we are using [towncrier](https://pypi.org/project/towncrier) to manage `CHANGES.rst`,  see https://github.com/plone/plone.releaser/blob/master/ADD-A-NEWS-ITEM.rst for all the details on how to work with it.

**Comment by nzambello** [comment]
@gforcada Added the news item for towncrier 👍

**Comment by nzambello** [comment]
Thank you @gforcada for the review and support!

**Pull request merged**
