### PR TITLE
Fix robots.txt

### PR DESCRIPTION
**Pull request by pbauer**
- Turn robots.txt into a browser-view
- Fix link to sitemap.xml.gz (include portal_url)
- Allow editing in site-controlpanel
 
Fixes https://github.com/plone/Products.CMFPlone/issues/604

### CODE REVIEW

**Comment by pbauer** [comment]
Jenkins PR-Job: http://jenkins.plone.org/job/pull-request-5.0/256

**Comment by pbauer** [comment]
Can some please review this? Does it needs a update-step to add the registry-value?

**Comment by vangheem** [comment]
Cool. Thanks for doing this. We'll need an upgrade step also.

**Comment by hvelarde** [comment]
nice enhancement! I'll contribute with a better default robots.txt later...

**Pull request merged**
