### PR TITLE
Get rid of qi

### PR DESCRIPTION
**Pull request by jensens**
implementation of PLIP plone/Products.CMFPlone#1340

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I (or you) can squash this if you like.

**Comment by hvelarde** [comment]
@mauritsvanrees wouldn't be nice to add a version number on all those warnings to let people know when they have to fix their stuff in advance?

BTW, thank you, now I know how to add warnings to my packages :-)

**Comment by mauritsvanrees** [comment]
@hvelarde What would you suggest as text? Something like this?

"listInstallableProducts is no longer supported since Plone 5.1. It will be removed in Plone 6.0."

**Comment by mauritsvanrees** [comment]
I have updated the warnings along those lines, and squashed the commits.  I will merge all now.

**Comment by gforcada** [comment]
@hvelarde you have http://docs.plone.org/develop/styleguide/deprecation.html as well

**Pull request merged**
