### PR TITLE
Make TinyMCE use the image-scales registered in imaging-controlpanel

### LINKED ISSUE #1717: TinyMCE does not use imagescales from imaging-controlpanel
When I configure scales in /@@imaging-controlpanel TinyMCE still shows the default since they are only hard-coded in the pattern (`mockup/patterns/tinymce/pattern.js`) and not overwritten by `Products.CMFPlone.patterns.PloneSettingsAdapter.tinymce`

### PR DESCRIPTION
**Pull request by pbauer**
Fixes #1717 and #1314

### CODE REVIEW

**Comment by thet** [comment]
hmhm... I've also fixed that, but differently.
I disliked the format, how the scales are passed to the pattern and made a JSON compatible string out of it.
See this commits:
https://github.com/plone/Products.CMFPlone/pull/1709/commits/b592563d3a340e526f69693df847e7c40f71225e
https://github.com/plone/mockup/pull/696/commits/c966d4603c2553ff1f534621978741f784e5252a

They are part of a PR with a much broader scope:
https://github.com/plone/mockup/pull/696

**Comment by pbauer** [comment]
@thet I did not see that. I prefer the json format. The old one was bizarre.

**Comment by idgserpro** [comment]
@pbauer this is related to #1393. You can check too?

**Comment by jensens** [comment]
so close this one in favor of the other one?

**Comment by thet** [comment]
Obsolete via https://github.com/plone/Products.CMFPlone/pull/1709

**Pull request closed without merging**
